// AST enrichment for the ratchet-facing Vix grammar. Structure remains
// grammar-derived; this file only names hidden enums, variants, and decoders.
ast({
  _item: { enum: "Item" },
  _statement: { enum: "Stmt" },
  _expr: { enum: "Expr" },
  _if_branch: { enum: "IfBranch" },
  _closure_body: { enum: "ClosureBody" },
  _type: { enum: "Type" },
  _pattern: { enum: "Pattern" },
  _variant_type_payload: { enum: "VariantTypePayload" },

  fn_item: { as: "Fn" },
  struct_item: { as: "Struct" },
  enum_item: { as: "Enum" },
  let_statement: { as: "Let", struct: "LetStmt" },
  yield_statement: { as: "Yield", struct: "YieldStmt" },
  expression_statement: { as: "Expression", struct: "ExpressionStmt" },
  if_expr: { as: "If" },
  field_access: {
    as: "Field",
    fields: { name: { enum: "Member" } },
  },
  method_call: { as: "MethodCall" },
  index_expr: { as: "Index" },
  array_expr: { as: "Array" },
  map_expr: { as: "Map" },
  set_expr: { as: "Set" },
  record_expr: { as: "Record" },
  variant_expr: { as: "Variant" },
  match_expr: { as: "Match" },
  closure_expr: { as: "Closure" },
  exec_expr: { as: "Exec" },
  try_expr: { as: "Try" },
  command_template: { as: "Command", decode: "text" },
  variant_pattern: { as: "Variant" },
  some_pattern: { as: "Some" },
  none_pattern: { as: "None" },
  binding_pattern: { as: "Binding" },
  string_pattern: { as: "Str" },
  number_pattern: { as: "Number" },
  wildcard_pattern: { as: "Wildcard" },
  variant_tuple_type: { as: "Tuple" },
  record_field_list: { as: "Record" },
  tuple_pattern: { as: "Tuple" },
  record_pattern: { as: "Record" },
  tuple_expr: { as: "Tuple" },
  generic_type: { as: "Generic" },
  array_type: { as: "Array" },
  tuple_type: { as: "Tuple" },
  function_type: { as: "Function" },
  type_path: { as: "Path" },

  identifier: { as: "Identifier", decode: "text" },
  string: { as: "Str", decode: "string" },
  number: { as: "Number", decode: "text" },
  tuple_index: { as: "Index", decode: "text" },
  boolean: { as: "Bool", decode: "bool" },
});
