// Generated by rapace-swift-codegen
// DO NOT EDIT

import Foundation
import Rapace
import Postcard

// MARK: - Types

public struct CountEvent: PostcardEncodable {
    public var value: UInt32
    public var remaining: UInt32
    
    public init(value: UInt32, remaining: UInt32) {
        self.value = value
        self.remaining = remaining
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(value)
        encoder.encode(remaining)
    }
}

public enum Status: PostcardEncodable {
    case pending
    case active
    case completed(result: String)
    case failed(error: String, code: Int32)
    
    public func encode(to encoder: inout PostcardEncoder) {
        switch self {
        case .pending:
            encoder.encode(UInt32(0))
        case .active:
            encoder.encode(UInt32(1))
        case .completed(let result):
            encoder.encode(UInt32(2))
            encoder.encode(result)
        case .failed(let error, let code):
            encoder.encode(UInt32(3))
            encoder.encode(error)
            encoder.encode(code)
        }
    }
}

public struct PhraseRequest: PostcardEncodable {
    public var phrase: String
    public var shout: Bool
    
    public init(phrase: String, shout: Bool) {
        self.phrase = phrase
        self.shout = shout
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(phrase)
        encoder.encode(shout)
    }
}

public struct PhraseResponse: PostcardEncodable {
    public var title: String
    public var original_len: UInt32
    
    public init(title: String, original_len: UInt32) {
        self.title = title
        self.original_len = original_len
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(title)
        encoder.encode(original_len)
    }
}

public struct NumbersRequest: PostcardEncodable {
    public var values: [Int32]
    
    public init(values: [Int32]) {
        self.values = values
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(values, using: { enc, val in val.encode(to: &enc) })
    }
}

public struct NumbersSummary: PostcardEncodable {
    public var sum: Int64
    public var mean: Double
    public var min: Int32
    public var max: Int32
    
    public init(sum: Int64, mean: Double, min: Int32, max: Int32) {
        self.sum = sum
        self.mean = mean
        self.min = min
        self.max = max
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(sum)
        encoder.encode(mean)
        encoder.encode(min)
        encoder.encode(max)
    }
}

public struct Person: PostcardEncodable {
    public var name: String
    public var age: UInt32
    public var email: String?
    public var tags: [String]
    
    public init(name: String, age: UInt32, email: String?, tags: [String]) {
        self.name = name
        self.age = age
        self.email = email
        self.tags = tags
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(name)
        encoder.encode(age)
        encoder.encode(email, using: { enc, val in val.encode(to: &enc) })
        encoder.encode(tags)
    }
}


// MARK: - Clients

public actor BrowserDemoClient {
    private let client: RapaceClient
    
    public init(client: RapaceClient) {
        self.client = client
    }
    
    public init(host: String, port: UInt16) async throws {
        self.client = try await RapaceClient(host: host, port: port)
    }
    
    // TODO: Streaming method countdown
    // public func countdown(_ start: UInt32) async throws -> AsyncStream<CountEvent> { ... }
    
    public func getStatus() async throws -> Status {
        let encoder = PostcardEncoder()
        
        let response = try await client.call(methodId: 0xBF6793B8, requestPayload: encoder.bytes)
        
        var data = Data(response)
        let variantIndex = try decodeVarint(from: &data)
        switch variantIndex {
        case 0:
            return .pending
        case 1:
            return .active
        case 2:
            let result_len = try decodeVarint(from: &data)
            let result_bytes = data.prefix(Int(result_len))
            data = data.dropFirst(Int(result_len))
            let result = String(data: Data(result_bytes), encoding: .utf8) ?? ""
            return .completed(result: result)
        case 3:
            let error_len = try decodeVarint(from: &data)
            let error_bytes = data.prefix(Int(error_len))
            data = data.dropFirst(Int(error_len))
            let error = String(data: Data(error_bytes), encoding: .utf8) ?? ""
            let code = Int32(try decodeSignedVarint(from: &data))
            return .failed(error: error, code: code)
        default:
            fatalError("Unknown Status variant: \(variantIndex)")
        }
    }
    
    public func transformPhrase(_ request: PhraseRequest) async throws -> PhraseResponse {
        var encoder = PostcardEncoder()
        request.encode(to: &encoder)
        
        let response = try await client.call(methodId: 0x3BD7EA46, requestPayload: encoder.bytes)
        
        var data = Data(response)
        let title_len = try decodeVarint(from: &data)
        let title_bytes = data.prefix(Int(title_len))
        data = data.dropFirst(Int(title_len))
        let title = String(data: Data(title_bytes), encoding: .utf8) ?? ""
        let original_len = UInt32(try decodeVarint(from: &data))
        return PhraseResponse(title: title, original_len: original_len)
    }
    
    public func summarizeNumbers(_ input: NumbersRequest) async throws -> NumbersSummary {
        var encoder = PostcardEncoder()
        input.encode(to: &encoder)
        
        let response = try await client.call(methodId: 0x270489F4, requestPayload: encoder.bytes)
        
        var data = Data(response)
        let sum = Int64(try decodeSignedVarint(from: &data))
        let mean_bytes = data.prefix(8)
        data = data.dropFirst(8)
        let mean = mean_bytes.withUnsafeBytes { $0.load(as: Double.self) }
        let min = Int32(try decodeSignedVarint(from: &data))
        let max = Int32(try decodeSignedVarint(from: &data))
        return NumbersSummary(sum: sum, mean: mean, min: min, max: max)
    }
    
    public func getPerson(_ name: String) async throws -> Person? {
        var encoder = PostcardEncoder()
        encoder.encode(name)
        
        let response = try await client.call(methodId: 0xB2584C93, requestPayload: encoder.bytes)
        
        var data = Data(response)
        let tag = data.removeFirst()
        if tag == 0 {
            return nil
        } else {
            let inner_name_len = try decodeVarint(from: &data)
            let inner_name_bytes = data.prefix(Int(inner_name_len))
            data = data.dropFirst(Int(inner_name_len))
            let inner_name = String(data: Data(inner_name_bytes), encoding: .utf8) ?? ""
            let inner_age = UInt32(try decodeVarint(from: &data))
            let inner_email: String?
            let optTag = data.removeFirst()
            if optTag == 0 {
                inner_email = nil
            } else {
                let inner_email_inner_len = try decodeVarint(from: &data)
                let inner_email_inner_bytes = data.prefix(Int(inner_email_inner_len))
                data = data.dropFirst(Int(inner_email_inner_len))
                let inner_email_inner = String(data: Data(inner_email_inner_bytes), encoding: .utf8) ?? ""
                inner_email = inner_email_inner
            }
            let inner_tags_count = try decodeVarint(from: &data)
            var inner_tags: [String] = []
            for _ in 0..<inner_tags_count {
                let inner_tags_item_len = try decodeVarint(from: &data)
                let inner_tags_item_bytes = data.prefix(Int(inner_tags_item_len))
                data = data.dropFirst(Int(inner_tags_item_len))
                let inner_tags_item = String(data: Data(inner_tags_item_bytes), encoding: .utf8) ?? ""
                inner_tags.append(inner_tags_item)
            }
            let inner = Person(name: inner_name, age: inner_age, email: inner_email, tags: inner_tags)
            return inner
        }
    }
    
}

