// Generated by rapace-swift-codegen
// DO NOT EDIT

import Foundation
import Rapace
import Postcard

// MARK: - Types

public struct ReadResult: PostcardEncodable {
    public var data: [UInt8]
    public var error: Int32
    
    public init(data: [UInt8], error: Int32) {
        self.data = data
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(data)
        encoder.encode(error)
    }
}

public enum ItemType: PostcardEncodable {
    case file
    case directory
    case symlink
    
    public func encode(to encoder: inout PostcardEncoder) {
        switch self {
        case .file:
            encoder.encode(UInt32(0))
        case .directory:
            encoder.encode(UInt32(1))
        case .symlink:
            encoder.encode(UInt32(2))
        }
    }
}

public struct CreateResult: PostcardEncodable {
    public var item_id: UInt64
    public var error: Int32
    
    public init(item_id: UInt64, error: Int32) {
        self.item_id = item_id
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(item_id)
        encoder.encode(error)
    }
}

public struct VfsResult: PostcardEncodable {
    public var error: Int32
    
    public init(error: Int32) {
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(error)
    }
}

public struct WriteResult: PostcardEncodable {
    public var bytes_written: UInt64
    public var error: Int32
    
    public init(bytes_written: UInt64, error: Int32) {
        self.bytes_written = bytes_written
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(bytes_written)
        encoder.encode(error)
    }
}

public struct ItemAttributes: PostcardEncodable {
    public var item_id: UInt64
    public var item_type: ItemType
    public var size: UInt64
    public var modified_time: UInt64
    public var created_time: UInt64
    public var mode: UInt32
    
    public init(item_id: UInt64, item_type: ItemType, size: UInt64, modified_time: UInt64, created_time: UInt64, mode: UInt32) {
        self.item_id = item_id
        self.item_type = item_type
        self.size = size
        self.modified_time = modified_time
        self.created_time = created_time
        self.mode = mode
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(item_id)
        item_type.encode(to: &encoder)
        encoder.encode(size)
        encoder.encode(modified_time)
        encoder.encode(created_time)
        encoder.encode(mode)
    }
}

public struct GetAttributesResult: PostcardEncodable {
    public var attrs: ItemAttributes
    public var error: Int32
    
    public init(attrs: ItemAttributes, error: Int32) {
        self.attrs = attrs
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        attrs.encode(to: &encoder)
        encoder.encode(error)
    }
}

public struct DirEntry: PostcardEncodable {
    public var name: String
    public var item_id: UInt64
    public var item_type: ItemType
    
    public init(name: String, item_id: UInt64, item_type: ItemType) {
        self.name = name
        self.item_id = item_id
        self.item_type = item_type
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(name)
        encoder.encode(item_id)
        item_type.encode(to: &encoder)
    }
}

public struct ReadDirResult: PostcardEncodable {
    public var entries: [DirEntry]
    public var next_cursor: UInt64
    public var error: Int32
    
    public init(entries: [DirEntry], next_cursor: UInt64, error: Int32) {
        self.entries = entries
        self.next_cursor = next_cursor
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(entries, using: { enc, val in val.encode(to: &enc) })
        encoder.encode(next_cursor)
        encoder.encode(error)
    }
}

public struct LookupResult: PostcardEncodable {
    public var item_id: UInt64
    public var item_type: ItemType
    public var error: Int32
    
    public init(item_id: UInt64, item_type: ItemType, error: Int32) {
        self.item_id = item_id
        self.item_type = item_type
        self.error = error
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(item_id)
        item_type.encode(to: &encoder)
        encoder.encode(error)
    }
}

public struct SetAttributesParams: PostcardEncodable {
    public var mode: UInt32?
    public var modified_time: UInt64?
    
    public init(mode: UInt32?, modified_time: UInt64?) {
        self.mode = mode
        self.modified_time = modified_time
    }
    
    public func encode(to encoder: inout PostcardEncoder) {
        encoder.encode(mode, using: { enc, val in val.encode(to: &enc) })
        encoder.encode(modified_time, using: { enc, val in val.encode(to: &enc) })
    }
}


// MARK: - Clients

public actor VfsClient {
    private let client: RapaceClient
    
    public init(client: RapaceClient) {
        self.client = client
    }
    
    public init(host: String, port: UInt16) async throws {
        self.client = try await RapaceClient(host: host, port: port)
    }
    
    public func read(item_id: UInt64, offset: UInt64, len: UInt64) async throws -> ReadResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        encoder.encode(offset)
        encoder.encode(len)
        
        let response = try await client.call(methodId: 0xC8C061C2, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let data_len = try decodeVarint(from: &responseData)
        let data = Array(responseData.prefix(Int(data_len)))
        responseData = responseData.dropFirst(Int(data_len))
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return ReadResult(data: data, error: error)
    }
    
    public func create(parent_id: UInt64, name: String, item_type: ItemType) async throws -> CreateResult {
        var encoder = PostcardEncoder()
        encoder.encode(parent_id)
        encoder.encode(name)
        encoder.encode(item_type)
        
        let response = try await client.call(methodId: 0x661F7793, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let item_id = UInt64(try decodeVarint(from: &responseData))
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return CreateResult(item_id: item_id, error: error)
    }
    
    public func rename(item_id: UInt64, new_parent_id: UInt64, new_name: String) async throws -> VfsResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        encoder.encode(new_parent_id)
        encoder.encode(new_name)
        
        let response = try await client.call(methodId: 0xACB29A5E, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return VfsResult(error: error)
    }
    
    public func write(item_id: UInt64, offset: UInt64, data: [UInt8]) async throws -> WriteResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        encoder.encode(offset)
        encoder.encode(data)
        
        let response = try await client.call(methodId: 0x103DB7BE, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let bytes_written = UInt64(try decodeVarint(from: &responseData))
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return WriteResult(bytes_written: bytes_written, error: error)
    }
    
    public func getAttributes(_ item_id: UInt64) async throws -> GetAttributesResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)

        let response = try await client.call(methodId: 0x7DFD6287, requestPayload: encoder.bytes)

        // Debug: print raw bytes
        let hexDump = response.map { String(format: "%02x", $0) }.joined(separator: " ")
        print("[getAttributes] Response (\(response.count) bytes): \(hexDump)")

        var responseData = Data(response)
        let attrs_item_id = UInt64(try decodeVarint(from: &responseData))
        print("[getAttributes] Decoded item_id: \(attrs_item_id)")

        let attrs_item_type_index = try decodeVarint(from: &responseData)
        print("[getAttributes] Decoded item_type_index: \(attrs_item_type_index)")
        let attrs_item_type: ItemType
        switch attrs_item_type_index {
        case 0:
            attrs_item_type = .file
        case 1:
            attrs_item_type = .directory
        case 2:
            attrs_item_type = .symlink
        default:
            fatalError("Unknown ItemType variant: \(attrs_item_type_index)")
        }
        let attrs_size = UInt64(try decodeVarint(from: &responseData))
        let attrs_modified_time = UInt64(try decodeVarint(from: &responseData))
        let attrs_created_time = UInt64(try decodeVarint(from: &responseData))
        let attrs_mode = UInt32(try decodeVarint(from: &responseData))
        let attrs = ItemAttributes(item_id: attrs_item_id, item_type: attrs_item_type, size: attrs_size, modified_time: attrs_modified_time, created_time: attrs_created_time, mode: attrs_mode)
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return GetAttributesResult(attrs: attrs, error: error)
    }
    
    public func readDir(item_id: UInt64, cursor: UInt64) async throws -> ReadDirResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        encoder.encode(cursor)
        
        let response = try await client.call(methodId: 0xC1C7A6DA, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let entries_count = try decodeVarint(from: &responseData)
        var entries: [DirEntry] = []
        for _ in 0..<entries_count {
            let entries_item_name_len = try decodeVarint(from: &responseData)
            let entries_item_name_bytes = responseData.prefix(Int(entries_item_name_len))
            responseData = responseData.dropFirst(Int(entries_item_name_len))
            let entries_item_name = String(data: Data(entries_item_name_bytes), encoding: .utf8) ?? ""
            let entries_item_item_id = UInt64(try decodeVarint(from: &responseData))
            let entries_item_item_type_index = try decodeVarint(from: &responseData)
            let entries_item_item_type: ItemType
            switch entries_item_item_type_index {
            case 0:
                entries_item_item_type = .file
            case 1:
                entries_item_item_type = .directory
            case 2:
                entries_item_item_type = .symlink
            default:
                fatalError("Unknown ItemType variant: \(entries_item_item_type_index)")
            }
            let entries_item = DirEntry(name: entries_item_name, item_id: entries_item_item_id, item_type: entries_item_item_type)
            entries.append(entries_item)
        }
        let next_cursor = UInt64(try decodeVarint(from: &responseData))
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return ReadDirResult(entries: entries, next_cursor: next_cursor, error: error)
    }
    
    public func delete(_ item_id: UInt64) async throws -> VfsResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        
        let response = try await client.call(methodId: 0x9EF34CDF, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return VfsResult(error: error)
    }
    
    public func lookup(parent_id: UInt64, name: String) async throws -> LookupResult {
        var encoder = PostcardEncoder()
        encoder.encode(parent_id)
        encoder.encode(name)
        
        let response = try await client.call(methodId: 0x5C3D01BF, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let item_id = UInt64(try decodeVarint(from: &responseData))
        let item_type_index = try decodeVarint(from: &responseData)
        let item_type: ItemType
        switch item_type_index {
        case 0:
            item_type = .file
        case 1:
            item_type = .directory
        case 2:
            item_type = .symlink
        default:
            fatalError("Unknown ItemType variant: \(item_type_index)")
        }
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return LookupResult(item_id: item_id, item_type: item_type, error: error)
    }
    
    public func setAttributes(item_id: UInt64, params: SetAttributesParams) async throws -> VfsResult {
        var encoder = PostcardEncoder()
        encoder.encode(item_id)
        encoder.encode(params)
        
        let response = try await client.call(methodId: 0xAD9BFFC6, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let error = Int32(try decodeSignedVarint(from: &responseData))
        return VfsResult(error: error)
    }
    
    public func ping() async throws -> String {
        let encoder = PostcardEncoder()
        
        let response = try await client.call(methodId: 0xB4BF98B1, requestPayload: encoder.bytes)
        
        var responseData = Data(response)
        let len = try decodeVarint(from: &responseData)
        let bytes = responseData.prefix(Int(len))
        return String(data: Data(bytes), encoding: .utf8) ?? ""
    }
    
}

