packages:
  - "styx-docs"
  - "editors/codemirror-styx"
  - "editors/monaco-styx"
  - "editors/vscode-styx"
  - "implementations/styx-js"
  - "tools/styx-webmd"
  - "styx-wasm"
  - "snark-wasm"
  - "playgrounds/monaco"
  - "playgrounds/codemirror"
  - "playgrounds/snark"
allowBuilds:
  '@swc/core': true
  esbuild: true
