//! vix — the demand-driven build language.
//!
//! v0 surface: parse vix source into the grammar-derived typed AST. The grammar
//! (playgrounds/snark/src/bundled/vix/grammar.js) is the single source of truth;
//! build.rs derives the AST types AND the resolved-CST lowering from its fields.
//! Nobody hand-writes the AST.

use snark::{
    grammar::RawGrammarJson,
    lexical::LexicalFacts,
    lower::weavy::{WeavyParsePlan, parse_prepared_weavy_with_report},
    parser::{ParseTable, ParserGrammar},
    validated::ValidatedGrammar,
};

/// The grammar-derived typed AST + lowering, generated by build.rs.
pub mod ast {
    include!(concat!(env!("OUT_DIR"), "/vix_ast.rs"));
}

pub mod binder;
pub(crate) mod data;
pub mod exec;
pub mod fetch;
pub mod ide;
pub mod machine;
pub(crate) mod module;
#[cfg(all(feature = "real-process", not(target_arch = "wasm32")))]
pub mod real_process;
pub mod reloc_selection;
#[cfg(all(feature = "runner-rpc", not(target_arch = "wasm32")))]
pub mod rpc_process;
pub mod value;

/// The tree-sitter grammar.json emitted from grammar.js at build time, embedded so
/// the runtime parser needs no JS engine.
pub const GRAMMAR_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/vix_grammar.json"));

/// The highlights query, embedded from the same bundle as the grammar — vix
/// owns its whole editor surface; clients need no grammar assets.
pub const HIGHLIGHTS_SCM: &str =
    include_str!("../../playgrounds/snark/src/bundled/vix/queries/highlights.scm");

/// A prepared vix parser: tables built once, reused across parses.
pub struct VixParser {
    parser: ParserGrammar,
    table: ParseTable,
    plan: WeavyParsePlan,
}

/// A parse failure. v0 carries a rendered message; wiring the grammar-generic derived
/// diagnostics (with state_stack) through here is the follow-up.
#[derive(Debug)]
pub struct ParseError {
    pub message: String,
}

impl core::fmt::Display for ParseError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for ParseError {}

impl VixParser {
    /// Build the parser from the embedded grammar. Failures here are build bugs —
    /// the same grammar is validated by this crate's tests — so this panics.
    pub fn new() -> Self {
        let raw = RawGrammarJson::from_tree_sitter_json_str(GRAMMAR_JSON)
            .expect("embedded vix grammar imports");
        let validated = ValidatedGrammar::from_raw(&raw).expect("embedded vix grammar validates");
        let lexical = LexicalFacts::from_grammar(&validated);
        let parser = ParserGrammar::normalize_from_validated(&validated, &lexical)
            .expect("embedded vix grammar normalizes")
            .prepare_productions_for_items()
            .expect("embedded vix grammar prepares productions");
        let table = ParseTable::from_grammar(&parser).expect("embedded vix grammar builds tables");
        let plan = WeavyParsePlan::new(&validated, &parser, &table).expect("weavy parse plan");
        Self {
            parser,
            table,
            plan,
        }
    }

    /// Run the embedded highlights query over `src`: (capture name, byte
    /// start, byte end) per capture, in document order.
    pub fn highlights(&self, src: &str) -> Result<Vec<(String, u32, u32)>, ParseError> {
        let report = parse_prepared_weavy_with_report(&self.plan, &self.parser, &self.table, src)
            .map_err(|e| ParseError {
            message: format!("parse failed: {e:?}"),
        })?;
        let events = report.accepted_tree_events();
        let query = snark::query::QuerySource(HIGHLIGHTS_SCM.to_string());
        let mut captures: Vec<(String, u32, u32)> = query
            .execute_highlights_from_tree_events(&self.parser, &events, src)
            .into_iter()
            .map(|c| {
                let bytes = c.bytes();
                (
                    c.capture_name().to_string(),
                    bytes.start().get(),
                    bytes.end().get(),
                )
            })
            .collect();
        // The query engine emits per-pattern; clients (editor decorations)
        // want document order.
        captures.sort_by_key(|&(_, start, end)| (start, end));
        Ok(captures)
    }

    /// Parse vix source into the typed AST.
    pub fn parse(&self, src: &str) -> Result<ast::SourceFile, ParseError> {
        let report = parse_prepared_weavy_with_report(&self.plan, &self.parser, &self.table, src)
            .map_err(|e| ParseError {
            message: format!("parse failed: {e:?}"),
        })?;
        let resolved = report
            .accepted_resolved_tree(&self.parser, src)
            .ok_or_else(|| ParseError {
                message: "no accepted parse".to_string(),
            })?;
        Ok(ast::lower_source_file(&resolved))
    }
}

impl Default for VixParser {
    fn default() -> Self {
        Self::new()
    }
}

/// Runtime support for the generated lowering.
pub mod support {
    use std::collections::BTreeMap;

    use snark::parser::ResolvedCstNode;

    /// Half-open byte range into the source, carried by every AST node.
    #[derive(facet::Facet, Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct Span {
        pub start: u32,
        pub end: u32,
    }

    impl Span {
        pub fn contains(&self, offset: u32) -> bool {
            self.start <= offset && offset < self.end
        }
    }

    /// A decoded leaf value plus where it came from — rename/go-to-def need the
    /// span of every identifier OCCURRENCE, not just of enclosing nodes.
    #[derive(facet::Facet, Debug, Clone, PartialEq)]
    pub struct Spanned<T> {
        pub value: T,
        pub span: Span,
    }

    impl<T> core::ops::Deref for Spanned<T> {
        type Target = T;
        fn deref(&self) -> &T {
            &self.value
        }
    }

    impl PartialEq<&str> for Spanned<String> {
        fn eq(&self, other: &&str) -> bool {
            self.value == *other
        }
    }

    /// This node's source span.
    pub fn span(n: &ResolvedCstNode) -> Span {
        let bytes = n.bytes();
        Span {
            start: bytes.start().get(),
            end: bytes.end().get(),
        }
    }

    /// All children carrying the given field.
    pub fn fields<'a>(
        n: &'a ResolvedCstNode,
        name: &'static str,
    ) -> impl Iterator<Item = &'a ResolvedCstNode> {
        n.children().iter().filter(move |c| c.field() == Some(name))
    }

    /// The single child carrying the given field; the grammar guarantees exactly one,
    /// so absence is a codegen/parser bug.
    pub fn field_one<'a>(n: &'a ResolvedCstNode, name: &str, kind: &str) -> &'a ResolvedCstNode {
        field_opt(n, name).unwrap_or_else(|| panic!("missing field `{name}` on `{kind}` node"))
    }

    pub fn field_opt<'a>(n: &'a ResolvedCstNode, name: &str) -> Option<&'a ResolvedCstNode> {
        n.children().iter().find(|c| c.field() == Some(name))
    }

    /// Raw source text of a node: its own token text, or its non-extra descendants'
    /// token texts concatenated in order (leaf nodes wrap one anonymous token).
    fn raw_text(n: &ResolvedCstNode) -> String {
        fn collect(n: &ResolvedCstNode, out: &mut String) {
            if let Some(t) = n.text() {
                out.push_str(t);
                return;
            }
            for c in n.children() {
                if !c.extra() {
                    collect(c, out);
                }
            }
        }
        let mut out = String::new();
        collect(n, &mut out);
        out
    }

    /// Raw-text leaf (identifier, number, flag, command token).
    pub fn node_text(n: &ResolvedCstNode) -> Spanned<String> {
        Spanned {
            value: raw_text(n),
            span: span(n),
        }
    }

    /// Token-valued fields (`field("op", …)`, `field("vis", "pub")`): snark drops
    /// `Field { child: None }` for anonymous token steps, so the generated lowering
    /// scans the node's direct anonymous children against the grammar-derived token
    /// set instead. The sets never collide with a node's other anonymous tokens.
    pub fn token_field(n: &ResolvedCstNode, set: &[&str]) -> Option<String> {
        n.children()
            .iter()
            .filter(|c| !c.named() && !c.extra())
            .find_map(|c| c.text().filter(|t| set.contains(t)).map(str::to_owned))
    }

    /// `"…"` string literal -> contents, escapes processed.
    pub fn decode_string(n: &ResolvedCstNode) -> Spanned<String> {
        Spanned {
            value: unquote(&raw_text(n)),
            span: span(n),
        }
    }

    /// `p"…"` path literal -> contents, escapes processed.
    pub fn decode_path(n: &ResolvedCstNode) -> Spanned<String> {
        let raw = raw_text(n);
        Spanned {
            value: unquote(raw.strip_prefix('p').unwrap_or(&raw)),
            span: span(n),
        }
    }

    /// `tmpl"…"` template literal -> contents, escapes processed.
    pub fn decode_template(n: &ResolvedCstNode) -> Spanned<String> {
        let raw = raw_text(n);
        Spanned {
            value: unquote(raw.strip_prefix("tmpl").unwrap_or(&raw)),
            span: span(n),
        }
    }

    pub fn decode_bool(n: &ResolvedCstNode) -> Spanned<bool> {
        Spanned {
            value: raw_text(n) == "true",
            span: span(n),
        }
    }

    fn unquote(raw: &str) -> String {
        let inner = raw
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .unwrap_or(raw);
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(ch) = chars.next() {
            if ch == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('r') => out.push('\r'),
                    Some(other) => out.push(other),
                    None => {}
                }
            } else {
                out.push(ch);
            }
        }
        out
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct PathMissing {
        pub path: String,
    }

    impl PathMissing {
        pub fn diagnostic(&self) -> String {
            format!("path `{}` is missing from resolved tree", self.path)
        }
    }

    pub(crate) fn subtree(
        tree: &crate::exec::Tree,
        path: &str,
    ) -> Result<crate::exec::Tree, String> {
        if let Some(contents) = tree.entries.get(path) {
            let base = path.rsplit_once('/').map(|(_, b)| b).unwrap_or(path);
            return Ok(crate::exec::Tree::of(&[(base, contents.as_str())]));
        }
        if let Some(contents) = tree.blobs.get(path) {
            let base = path.rsplit_once('/').map(|(_, b)| b).unwrap_or(path);
            return Ok(crate::exec::Tree::of_blobs(&[(base, contents.as_slice())]));
        }
        let prefix = format!("{path}/");
        let entries: BTreeMap<String, String> = tree
            .entries
            .iter()
            .filter_map(|(k, v)| k.strip_prefix(&prefix).map(|r| (r.to_string(), v.clone())))
            .collect();
        let blobs: BTreeMap<String, Vec<u8>> = tree
            .blobs
            .iter()
            .filter_map(|(k, v)| k.strip_prefix(&prefix).map(|r| (r.to_string(), v.clone())))
            .collect();
        if entries.is_empty() && blobs.is_empty() {
            return Err(format!("no `{path}` in tree"));
        }
        Ok(crate::exec::Tree { entries, blobs })
    }

    pub(crate) fn tree_text(tree: &crate::exec::Tree, path: &str) -> Result<String, String> {
        if let Some(contents) = tree.entries.get(path) {
            return Ok(contents.clone());
        }
        if let Some(contents) = tree.blobs.get(path) {
            return String::from_utf8(contents.clone()).map_err(|err| err.to_string());
        }
        let prefix = format!("{path}/");
        if tree
            .entries
            .keys()
            .chain(tree.blobs.keys())
            .any(|key| key.starts_with(&prefix))
        {
            return Err(format!("path `{path}` is a directory, not a file"));
        }
        Err(format!("no `{path}` in tree"))
    }

    pub(crate) fn assign_roles(
        command: &str,
        argv: &[String],
    ) -> Result<crate::exec::ExecPlan, String> {
        use crate::exec::Role;
        let mut out = Vec::new();
        match command {
            "cc" => {
                let mut prev: Option<&str> = None;
                for arg in argv {
                    let role = match prev {
                        Some("-o") => Role::Output,
                        Some("-I") => Role::SearchDir,
                        _ if arg.starts_with("/m/") => Role::Input,
                        _ => Role::Flag,
                    };
                    out.push((arg.clone(), role));
                    prev = Some(arg.as_str());
                }
            }
            "ar" => {
                for arg in argv {
                    let role = if arg.starts_with("/m/") {
                        crate::exec::Role::Input
                    } else if arg == "rcs" {
                        Role::Flag
                    } else {
                        Role::Output
                    };
                    out.push((arg.clone(), role));
                }
            }
            "rustc" => {
                let mut prev: Option<&str> = None;
                for arg in argv {
                    let role = match prev {
                        Some("-o") => Role::Output,
                        Some("-L") if arg.contains("/m/") => Role::SearchDirFlag,
                        Some("-L") => Role::Flag,
                        Some("--extern") if arg.contains("/m/") => Role::InputFlag,
                        Some("--extern") => Role::Flag,
                        Some("--env") => Role::Env,
                        Some("--stdout") => Role::Stdout,
                        _ if arg.starts_with("/m/") => Role::Input,
                        _ if arg.starts_with("--emit=") && arg.contains('=') => Role::OutputFlag,
                        _ if arg.starts_with("-L") && arg.contains("/m/") => Role::SearchDirFlag,
                        _ if arg.starts_with("--extern") && arg.contains("/m/") => Role::InputFlag,
                        _ => Role::Flag,
                    };
                    out.push((arg.clone(), role));
                    prev = Some(arg.as_str());
                }
            }
            "build_script" => {
                let mut prev: Option<&str> = None;
                for arg in argv {
                    let role = match prev {
                        Some("--executable") => Role::Executable,
                        Some("--stdout") => Role::Stdout,
                        Some("--out-dir") => Role::OutputDir,
                        Some("--env") => Role::Env,
                        _ => Role::Flag,
                    };
                    out.push((arg.clone(), role));
                    prev = Some(arg.as_str());
                }
            }
            other => return Err(format!("no command grammar for `{other}`")),
        }
        Ok(crate::exec::ExecPlan { argv: out })
    }

    pub(crate) fn tool_for(command: &str) -> Result<&'static dyn crate::exec::Tool, String> {
        match command {
            "cc" => Ok(&crate::exec::FakeCc),
            "ar" => Ok(&crate::exec::FakeAr),
            "rustc" => Ok(&crate::exec::FakeRustc),
            "build_script" => Ok(&crate::exec::FakeBuildScript),
            other => Err(format!("no tool for `{other}`")),
        }
    }
}
