import { test, expect } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface TestCase {
  name: string;
  old_body_html: string;
  new_body_html: string;
  patches_json: string;
}

// Load test cases generated by Rust
const testCasesPath = path.join(__dirname, "..", "test-cases.json");

let testCases: TestCase[] = [];

try {
  testCases = JSON.parse(fs.readFileSync(testCasesPath, "utf-8"));
} catch (e) {
  console.warn("No test-cases.json found, using minimal test set");
  testCases = [
    {
      name: "simple_text_change",
      old_body_html: "<p>Hello</p>",
      new_body_html: "<p>World</p>",
      patches_json: JSON.stringify([{ SetText: { path: [0, 0], text: "World" } }]),
    },
  ];
}

test.describe("facet-html-diff WASM", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/index.html");
    await page.waitForFunction(() => (window as any).wasmReady === true, { timeout: 10000 });
  });

  test("WASM module loads", async ({ page }) => {
    const status = await page.textContent("#status");
    expect(status).toBe("WASM loaded successfully");
  });

  for (const tc of testCases) {
    test(`roundtrip: ${tc.name}`, async ({ page }) => {
      const result = await page.evaluate(async (testCase) => {
        return await (window as any).runTestCase(testCase);
      }, tc);

      expect(result.pass, result.error || "").toBe(true);
    });
  }
});
