//! Fable: a tiny typed language over Facet-reflected Rust values.
//!
//! Fable parses through its snark grammar, lowers the generated typed AST toward
//! canonical Weavy IR, and executes reusable plans over live reflected values.

use snark::{
    grammar::RawGrammarJson,
    lexical::LexicalFacts,
    lower::weavy::{WeavyParsePlan, parse_prepared_weavy_with_report},
    parser::{ParseTable, ParserGrammar},
    validated::ValidatedGrammar,
};

/// The grammar-derived typed AST + resolved-CST lowering generated by build.rs.
pub mod ast {
    include!(concat!(env!("OUT_DIR"), "/fable_ast.rs"));
}

mod lowering;
pub use lowering::{
    FableError, FableField, FableFieldBoolUnary, FableFieldMut, FableFieldMutUnary,
    FableFieldStringUnary, FableFloatUnary, FableIntrinsics, FablePlan, FablePredicatePlan,
    FableQueryPlan, FableQueryResult, FableQueryType, FableRootAccess, FableRootPlan,
    FableRootPredicatePlan, FableRootQueryPlan, FableRootSpec, FableRootValue, FableSignedUnary,
    FableStringBinaryPredicate, FableStringUnary, FableTransformPlan, FableUnsignedUnary, apply,
    apply_with_intrinsics, predicate, predicate_with_intrinsics, query, query_with_intrinsics,
    transform, transform_with_intrinsics,
};

/// The tree-sitter grammar.json emitted from grammar.js at build time.
pub const GRAMMAR_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/fable_grammar.json"));

/// A prepared fable parser: tables built once, reused across parses.
pub struct FableParser {
    parser: ParserGrammar,
    table: ParseTable,
    plan: WeavyParsePlan,
}

/// A parse failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseError {
    pub message: String,
}

impl core::fmt::Display for ParseError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for ParseError {}

impl FableParser {
    /// Build the parser from the embedded grammar.
    #[must_use]
    pub fn new() -> Self {
        let raw = RawGrammarJson::from_tree_sitter_json_str(GRAMMAR_JSON)
            .expect("embedded fable grammar imports");
        let validated = ValidatedGrammar::from_raw(&raw).expect("embedded fable grammar validates");
        let lexical = LexicalFacts::from_grammar(&validated);
        let parser = ParserGrammar::normalize_from_validated(&validated, &lexical)
            .expect("embedded fable grammar normalizes")
            .prepare_productions_for_items()
            .expect("embedded fable grammar prepares productions");
        let table =
            ParseTable::from_grammar(&parser).expect("embedded fable grammar builds tables");
        let plan = WeavyParsePlan::new(&validated, &parser, &table).expect("weavy parse plan");
        Self {
            parser,
            table,
            plan,
        }
    }

    /// Parse fable source into the generated typed AST.
    pub fn parse(&self, src: &str) -> Result<ast::SourceFile, ParseError> {
        let report = parse_prepared_weavy_with_report(&self.plan, &self.parser, &self.table, src)
            .map_err(|error| ParseError {
            message: format!("parse failed: {error:?}"),
        })?;
        let resolved = report
            .accepted_resolved_tree(&self.parser, src)
            .ok_or_else(|| ParseError {
                message: "no accepted parse".to_string(),
            })?;
        Ok(ast::lower_source_file(&resolved))
    }
}

impl Default for FableParser {
    fn default() -> Self {
        Self::new()
    }
}

/// Parse fable source into the generated typed AST.
pub fn parse(src: &str) -> Result<ast::SourceFile, ParseError> {
    FableParser::new().parse(src)
}

#[cfg(test)]
mod tests {
    use super::ast::{Expr, Item, Literal, MatchPattern, Name, Stmt, TypeExpr};
    use super::support::Span;
    use super::{FableParser, parse};

    fn span_for(src: &str, needle: &str) -> Span {
        let start = src.find(needle).expect("needle exists") as u32;
        Span {
            start,
            end: start + needle.len() as u32,
        }
    }

    #[test]
    fn malformed_inputs_return_parse_errors() {
        let parser = FableParser::new();

        for src in [
            "root.age = ; root.ok = true",
            "if root.age { root.ok = true",
            "root.items[",
        ] {
            let err = parser.parse(src).expect_err("malformed input must fail");
            assert!(!err.message.is_empty());
            assert!(err.message == "no accepted parse" || err.message.starts_with("parse failed:"));
        }
    }

    #[test]
    fn generated_ast_preserves_statement_and_leaf_spans() {
        let src = "let answer = 42;";
        let root = parse(src).expect("valid fable source");

        assert_eq!(
            root.span,
            Span {
                start: 0,
                end: src.len() as u32,
            }
        );

        let [Item::Stmt(Stmt::Let(stmt))] = root.items.as_slice() else {
            panic!("expected one let statement");
        };
        assert_eq!(
            stmt.span,
            Span {
                start: 0,
                end: src.len() as u32,
            }
        );

        let Name::Ident(name) = &stmt.name else {
            panic!("expected identifier binding name");
        };
        assert_eq!(name.value, "answer");
        assert_eq!(name.span, span_for(src, "answer"));

        let Expr::Literal(Literal::Int(value)) = &stmt.value else {
            panic!("expected integer literal value");
        };
        assert_eq!(value.value, "42");
        assert_eq!(value.span, span_for(src, "42"));
    }

    #[test]
    fn generated_ast_covers_declared_types_and_match() {
        let src = r#"
struct Point { x: i64, y: i64, }
enum Shape {
  Empty,
  Point { point: Point, },
}
let shape = Shape::Point { point: Point { x: 1, y: 2 } };
match shape {
  Shape::Point { point } => { point.x; },
  _ => { 0; },
}
"#;
        let root = parse(src).expect("valid fable source");

        let [
            Item::Struct(struct_decl),
            Item::Enum(enum_decl),
            Item::Stmt(Stmt::Let(let_stmt)),
            Item::Stmt(Stmt::Expr(expr_stmt)),
        ] = root.items.as_slice()
        else {
            panic!("expected struct, enum, let, match expression items");
        };

        assert_eq!(struct_decl.name.value, "Point");
        assert_eq!(struct_decl.fields.fields.len(), 2);
        let TypeExpr::Scalar(first_field_ty) = &struct_decl.fields.fields[0].ty else {
            panic!("expected scalar field type");
        };
        assert_eq!(first_field_ty.value, "i64");

        assert_eq!(enum_decl.name.value, "Shape");
        assert_eq!(enum_decl.variants.len(), 2);
        assert_eq!(enum_decl.variants[1].name.value, "Point");
        assert_eq!(
            enum_decl.variants[1]
                .fields
                .as_ref()
                .expect("payload fields")
                .fields
                .len(),
            1,
        );

        let Expr::EnumVariant(constructor) = &let_stmt.value else {
            panic!("expected enum variant constructor");
        };
        assert_eq!(constructor.path.type_name.value, "Shape");
        assert_eq!(constructor.path.variant_name.value, "Point");
        assert_eq!(
            constructor
                .fields
                .as_ref()
                .expect("constructor payload")
                .fields
                .len(),
            1,
        );

        let Expr::Match(match_expr) = &expr_stmt.expr else {
            panic!("expected match expression");
        };
        assert_eq!(match_expr.arms.len(), 2);
        let MatchPattern::Variant(pattern) = &match_expr.arms[0].pattern else {
            panic!("expected variant pattern");
        };
        assert_eq!(pattern.path.type_name.value, "Shape");
        assert_eq!(pattern.path.variant_name.value, "Point");
        assert_eq!(
            pattern
                .fields
                .as_ref()
                .expect("pattern payload")
                .fields
                .len(),
            1,
        );
        let MatchPattern::Wildcard(wildcard) = &match_expr.arms[1].pattern else {
            panic!("expected wildcard pattern");
        };
        assert_eq!(wildcard.value, "_");
    }

    #[test]
    fn generated_ast_covers_function_declarations() {
        let src = r#"
fn add_one(value: i64) -> i64 {
  value + 1;
}
"#;
        let root = parse(src).expect("valid fable source");

        let [Item::Fn(function)] = root.items.as_slice() else {
            panic!("expected one function declaration");
        };
        assert_eq!(function.name.value, "add_one");
        assert_eq!(function.params.params.len(), 1);
        let Name::Ident(param_name) = &function.params.params[0].name else {
            panic!("expected identifier parameter name");
        };
        assert_eq!(param_name.value, "value");
        let TypeExpr::Scalar(param_ty) = &function.params.params[0].ty else {
            panic!("expected scalar parameter type");
        };
        assert_eq!(param_ty.value, "i64");
        let TypeExpr::Scalar(return_ty) = &function.return_ty else {
            panic!("expected scalar return type");
        };
        assert_eq!(return_ty.value, "i64");
        assert_eq!(function.body.stmts.len(), 1);
    }
}

/// Runtime support for the generated snark AST lowering.
pub mod support {
    use snark::parser::ResolvedCstNode;

    /// Half-open byte range into the source, carried by every AST node.
    #[derive(facet::Facet, Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct Span {
        pub start: u32,
        pub end: u32,
    }

    impl Span {
        pub fn contains(&self, offset: u32) -> bool {
            self.start <= offset && offset < self.end
        }
    }

    /// A decoded leaf value plus its source span.
    #[derive(facet::Facet, Debug, Clone, PartialEq)]
    pub struct Spanned<T> {
        pub value: T,
        pub span: Span,
    }

    impl<T> core::ops::Deref for Spanned<T> {
        type Target = T;

        fn deref(&self) -> &T {
            &self.value
        }
    }

    impl PartialEq<&str> for Spanned<String> {
        fn eq(&self, other: &&str) -> bool {
            self.value == *other
        }
    }

    pub fn span(n: &ResolvedCstNode) -> Span {
        let bytes = n.bytes();
        Span {
            start: bytes.start().get(),
            end: bytes.end().get(),
        }
    }

    pub fn fields<'a>(
        n: &'a ResolvedCstNode,
        name: &'static str,
    ) -> impl Iterator<Item = &'a ResolvedCstNode> {
        n.children().iter().filter(move |c| c.field() == Some(name))
    }

    pub fn field_one<'a>(n: &'a ResolvedCstNode, name: &str, kind: &str) -> &'a ResolvedCstNode {
        field_opt(n, name).unwrap_or_else(|| panic!("missing field `{name}` on `{kind}` node"))
    }

    pub fn field_opt<'a>(n: &'a ResolvedCstNode, name: &str) -> Option<&'a ResolvedCstNode> {
        n.children().iter().find(|c| c.field() == Some(name))
    }

    fn raw_text(n: &ResolvedCstNode) -> String {
        fn collect(n: &ResolvedCstNode, out: &mut String) {
            if let Some(t) = n.text() {
                out.push_str(t);
                return;
            }
            for c in n.children() {
                if !c.extra() {
                    collect(c, out);
                }
            }
        }
        let mut out = String::new();
        collect(n, &mut out);
        out
    }

    pub fn node_text(n: &ResolvedCstNode) -> Spanned<String> {
        Spanned {
            value: raw_text(n),
            span: span(n),
        }
    }

    pub fn token_field(n: &ResolvedCstNode, set: &[&str]) -> Option<String> {
        n.children()
            .iter()
            .filter(|c| !c.named() && !c.extra())
            .find_map(|c| c.text().filter(|t| set.contains(t)).map(str::to_owned))
    }

    pub fn decode_string(n: &ResolvedCstNode) -> Spanned<String> {
        Spanned {
            value: unquote(&raw_text(n)),
            span: span(n),
        }
    }

    pub fn decode_path(n: &ResolvedCstNode) -> Spanned<String> {
        let raw = raw_text(n);
        Spanned {
            value: unquote(raw.strip_prefix('p').unwrap_or(&raw)),
            span: span(n),
        }
    }

    pub fn decode_bool(n: &ResolvedCstNode) -> Spanned<bool> {
        Spanned {
            value: raw_text(n) == "true",
            span: span(n),
        }
    }

    fn unquote(raw: &str) -> String {
        let Some(quote) = raw.chars().next() else {
            return String::new();
        };
        let inner = raw
            .strip_prefix(quote)
            .and_then(|s| s.strip_suffix(quote))
            .unwrap_or(raw);
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(ch) = chars.next() {
            if ch == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('r') => out.push('\r'),
                    Some(other) => out.push(other),
                    None => {}
                }
            } else {
                out.push(ch);
            }
        }
        out
    }
}
