//! Build-time stencil extraction.
//!
//! On Apple Silicon, compile the Rust stencils with rustc (`--emit=obj`) and pull
//! each stencil's machine code — and its `phon_cont` relocation offsets — out of
//! the object file with the `object` crate, emitting a generated Rust file the
//! crate `include!`s. rustc (LLVM) performs all instruction selection; this
//! script only reads bytes and relocation offsets back out.
//!
//! Prefer nightly with `--cfg tailcall` so the stencils chain via guaranteed
//! tail calls (`become`) — one stack frame, no per-op call/return. Fall back to a
//! stable, call-based compile when nightly is absent; both extract identically
//! (the continuation branch is `BRANCH26` to `phon_cont` either way). When the
//! tail-call build is used, set `--cfg phon_jit_tailcall` so the crate can report
//! it.
//!
//! Why a separate object at all: copy-and-patch must *patch* the continuation
//! branch, which needs the relocation table — present only in the pre-link
//! object, not the linked binary.
//!
//! On every other target we emit an empty table; the portable threaded executor
//! is the fallback there.

use std::{env, fs, path::Path, path::PathBuf, process::Command};

fn main() {
    // Declared here (always) so the cfg is known on every target, even those
    // where it is never set.
    println!("cargo:rustc-check-cfg=cfg(phon_jit_tailcall)");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated = out.join("stencils.rs");

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    if target_os == "macos" && target_arch == "aarch64" {
        emit_arm64_macos(&out, &generated);
    } else {
        fs::write(
            &generated,
            "pub const SMOKE: &[u8] = &[];\n\
             pub const SCALAR: &[u8] = &[];\n\
             pub const SCALAR_CONT: &[usize] = &[];\n\
             pub const SEQUENCE: &[u8] = &[];\n\
             pub const SEQUENCE_CONT: &[usize] = &[];\n\
             pub const DONE: &[u8] = &[];\n",
        )
        .unwrap();
    }
}

fn emit_arm64_macos(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/stencils.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-check-cfg=cfg(phon_jit_tailcall)");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("stencils.o");

    // Prefer nightly tail-call stencils; fall back to stable call-based ones.
    let tailcall = nightly_available() && compile("rustc", &["+nightly"], &obj, &target, true);
    if tailcall {
        println!("cargo:rustc-cfg=phon_jit_tailcall");
    } else {
        let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
        assert!(
            compile(&rustc, &[], &obj, &target, false),
            "rustc failed to compile stencils"
        );
    }

    let bytes = fs::read(&obj).unwrap();
    let smoke = extract(&bytes, "phon_stencil_smoke");
    let scalar = extract(&bytes, "phon_stencil_scalar");
    let sequence = extract(&bytes, "phon_stencil_sequence");
    let done = extract(&bytes, "phon_stencil_done");

    let mode = if tailcall { "tail-call (nightly become)" } else { "call (stable)" };
    let mut src = String::new();
    src.push_str(&format!(
        "// Generated by build.rs from stencils/stencils.rs (rustc --emit=obj, {mode}).\n"
    ));
    src.push_str(&format!(
        "/// `phon_stencil_smoke` (x*3+1) machine code; no relocations.\n\
         pub const SMOKE: &[u8] = &{:?};\n",
        smoke.bytes
    ));
    src.push_str(&format!(
        "/// `phon_stencil_scalar` machine code: decode one fixed scalar, continue.\n\
         pub const SCALAR: &[u8] = &{:?};\n",
        scalar.bytes
    ));
    src.push_str(&format!(
        "/// Byte offsets within `SCALAR` of the `phon_cont` continuation branches\n\
         /// to patch (`BRANCH26`).\n\
         pub const SCALAR_CONT: &[usize] = &{:?};\n",
        scalar.cont_relocs
    ));
    src.push_str(&format!(
        "/// `phon_stencil_sequence` machine code: decode one owned sequence,\n\
         /// continue. The element body is invoked through `SeqInfo.element_entry`.\n\
         pub const SEQUENCE: &[u8] = &{:?};\n",
        sequence.bytes
    ));
    src.push_str(&format!(
        "/// Byte offsets within `SEQUENCE` of the `phon_cont` continuation branch\n\
         /// to patch (`BRANCH26`).\n\
         pub const SEQUENCE_CONT: &[usize] = &{:?};\n",
        sequence.cont_relocs
    ));
    src.push_str(&format!(
        "/// `phon_stencil_done` machine code: a lone `ret`.\n\
         pub const DONE: &[u8] = &{:?};\n",
        done.bytes
    ));
    fs::write(generated, src).unwrap();
}

fn nightly_available() -> bool {
    Command::new("rustc")
        .args(["+nightly", "--version"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Compile the stencils to `obj`. Returns whether it succeeded; output is
/// captured so a clean build stays quiet (and a failed nightly attempt falls back
/// silently).
fn compile(program: &str, pre_args: &[&str], obj: &Path, target: &str, tailcall: bool) -> bool {
    let mut cmd = Command::new(program);
    cmd.args(pre_args);
    cmd.args([
        "--edition",
        "2021",
        "--emit=obj",
        "--crate-type=lib",
        "-O",
        "-C",
        "panic=abort",
        "--target",
        target,
    ]);
    if tailcall {
        cmd.args(["--cfg", "tailcall"]);
    }
    cmd.arg("-o").arg(obj).arg("stencils/stencils.rs");
    match cmd.output() {
        Ok(o) if o.status.success() => true,
        Ok(o) => {
            // Surface the error only for the stable path (the final attempt).
            if pre_args.is_empty() {
                eprint!("{}", String::from_utf8_lossy(&o.stderr));
            }
            false
        }
        Err(_) => false,
    }
}

struct Stencil {
    bytes: Vec<u8>,
    /// Offsets, relative to the stencil's start, of `BRANCH26` relocations
    /// targeting `phon_cont`.
    cont_relocs: Vec<usize>,
}

/// Extract one stencil's bytes and continuation relocations from the object's
/// `__text` section by symbol name.
fn extract(obj: &[u8], symbol: &str) -> Stencil {
    use object::{Object, ObjectSection, ObjectSymbol, RelocationTarget};

    let file = object::File::parse(obj).expect("parse object file");
    let text = file
        .sections()
        .find(|s| s.name() == Ok("__text"))
        .expect("no __text section");
    let data = text.data().expect("read __text data");
    let text_index = text.index();

    let addr_of = |suffix: &str| -> u64 {
        file.symbols()
            .find(|s| {
                s.section_index() == Some(text_index)
                    && s.name().is_ok_and(|n| n.ends_with(suffix))
            })
            .unwrap_or_else(|| panic!("symbol {suffix} not found"))
            .address()
    };
    let mut boundaries: Vec<u64> = [
        "phon_stencil_smoke",
        "phon_stencil_scalar",
        "phon_stencil_sequence",
        "phon_stencil_done",
    ]
    .iter()
    .map(|s| addr_of(s))
    .collect();
    boundaries.push(data.len() as u64);
    boundaries.sort_unstable();

    let start = addr_of(symbol);
    let end = *boundaries
        .iter()
        .find(|&&b| b > start)
        .expect("a boundary past the stencil");

    let bytes = data[start as usize..end as usize].to_vec();

    let mut cont_relocs = Vec::new();
    for (offset, reloc) in text.relocations() {
        if offset < start || offset >= end {
            continue;
        }
        if let RelocationTarget::Symbol(idx) = reloc.target()
            && let Ok(sym) = file.symbol_by_index(idx)
            && sym.name().is_ok_and(|n| n.ends_with("phon_cont"))
        {
            cont_relocs.push((offset - start) as usize);
        }
    }
    cont_relocs.sort_unstable();

    Stencil { bytes, cont_relocs }
}
