//! ⚠️  AUTO-GENERATED by benchmark-generator ⚠️
//!
//! ❌ DO NOT EDIT THIS FILE DIRECTLY
//! ✅ Instead, edit: facet-perf-shootout/benches/json.kdl
//!
//! To regenerate: cargo xtask gen-benchmarks

#![allow(dead_code)]
#![allow(unused_imports)]

use facet::Facet;
use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct SimpleRecord {
    id: u64,
    name: String,
    active: bool,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct ShortKeys {
    id: u64,      // 2 chars
    name: String, // 4 chars
    age: i64,     // 3 chars
    ok: bool,     // 2 chars
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct MediumKeys {
    #[facet(rename = "userId")]
    #[serde(rename = "userId")]
    user_id: u64, // 6 chars
    #[facet(rename = "userName")]
    #[serde(rename = "userName")]
    user_name: String, // 8 chars
    #[facet(rename = "isActive")]
    #[serde(rename = "isActive")]
    is_active: bool, // 8 chars
    counter: i64, // 7 chars
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct LongKeys {
    #[facet(rename = "userIdentifier")]
    #[serde(rename = "userIdentifier")]
    user_identifier: u64, // 14 chars
    #[facet(rename = "displayNameValue")]
    #[serde(rename = "displayNameValue")]
    display_name_value: String, // 16 chars
    #[facet(rename = "isCurrentlyActive")]
    #[serde(rename = "isCurrentlyActive")]
    is_currently_active: bool, // 17 chars
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Nest1 {
    id: u64,
    val: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Nest2 {
    id: u64,
    inner: Nest1,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Nest3 {
    id: u64,
    inner: Nest2,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Inner {
    x: i64,
    y: i64,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Outer {
    id: u64,
    inner: Inner,
    name: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct WithOptions {
    id: u64,
    maybe_count: Option<i64>,
    maybe_flag: Option<bool>,
    maybe_value: Option<f64>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct NestedOuter {
    id: u64,
    inner: NestedInner,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct NestedInner {
    name: String,
    value: f64,
    deep: NestedDeep,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct NestedDeep {
    flag: bool,
    count: u32,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct OptionsMaybeData {
    required: u64,
    optional_string: Option<String>,
    optional_number: Option<f64>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct TwitterResponseSparse {
    statuses: Vec<StatusSparse>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct StatusSparse {
    id: u64,
    text: String,
    user: UserSparse,
    retweet_count: u32,
    favorite_count: u32,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct UserSparse {
    id: u64,
    screen_name: String,
    followers_count: u32,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Canada {
    #[facet(rename = "type")]
    #[serde(rename = "type")]
    type_: String,
    features: Vec<Feature>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Feature {
    #[facet(rename = "type")]
    #[serde(rename = "type")]
    type_: String,
    properties: Properties,
    geometry: Geometry,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Properties {
    name: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Geometry {
    #[facet(rename = "type")]
    #[serde(rename = "type")]
    type_: String,
    coordinates: Vec<Vec<Vec<f64>>>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct CitmCatalog {
    #[serde(rename = "areaNames")]
    #[facet(rename = "areaNames")]
    area_names: std::collections::HashMap<String, String>,
    #[serde(rename = "audienceSubCategoryNames")]
    #[facet(rename = "audienceSubCategoryNames")]
    audience_sub_category_names: std::collections::HashMap<String, String>,
    #[serde(rename = "blockNames")]
    #[facet(rename = "blockNames")]
    block_names: std::collections::HashMap<String, String>,
    events: std::collections::HashMap<String, Event>,
    performances: Vec<Performance>,
    #[serde(rename = "seatCategoryNames")]
    #[facet(rename = "seatCategoryNames")]
    seat_category_names: std::collections::HashMap<String, String>,
    #[serde(rename = "subTopicNames")]
    #[facet(rename = "subTopicNames")]
    sub_topic_names: std::collections::HashMap<String, String>,
    #[serde(rename = "subjectNames")]
    #[facet(rename = "subjectNames")]
    subject_names: std::collections::HashMap<String, String>,
    #[serde(rename = "topicNames")]
    #[facet(rename = "topicNames")]
    topic_names: std::collections::HashMap<String, String>,
    #[serde(rename = "topicSubTopics")]
    #[facet(rename = "topicSubTopics")]
    topic_sub_topics: std::collections::HashMap<String, Vec<u64>>,
    #[serde(rename = "venueNames")]
    #[facet(rename = "venueNames")]
    venue_names: std::collections::HashMap<String, String>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Event {
    description: Option<String>,
    id: u64,
    logo: Option<String>,
    name: String,
    #[serde(rename = "subTopicIds")]
    #[facet(rename = "subTopicIds")]
    sub_topic_ids: Vec<u64>,
    #[serde(rename = "subjectCode")]
    #[facet(rename = "subjectCode")]
    subject_code: Option<String>,
    subtitle: Option<String>,
    #[serde(rename = "topicIds")]
    #[facet(rename = "topicIds")]
    topic_ids: Vec<u64>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Performance {
    #[serde(rename = "eventId")]
    #[facet(rename = "eventId")]
    event_id: u64,
    id: u64,
    logo: Option<String>,
    name: Option<String>,
    prices: Vec<Price>,
    #[serde(rename = "seatCategories")]
    #[facet(rename = "seatCategories")]
    seat_categories: Vec<SeatCategory>,
    #[serde(rename = "seatMapImage")]
    #[facet(rename = "seatMapImage")]
    seat_map_image: Option<String>,
    start: u64,
    #[serde(rename = "venueCode")]
    #[facet(rename = "venueCode")]
    venue_code: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Price {
    amount: u64,
    #[serde(rename = "audienceSubCategoryId")]
    #[facet(rename = "audienceSubCategoryId")]
    audience_sub_category_id: u64,
    #[serde(rename = "seatCategoryId")]
    #[facet(rename = "seatCategoryId")]
    seat_category_id: u64,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct SeatCategory {
    areas: Vec<Area>,
    #[serde(rename = "seatCategoryId")]
    #[facet(rename = "seatCategoryId")]
    seat_category_id: u64,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Area {
    #[serde(rename = "areaId")]
    #[facet(rename = "areaId")]
    area_id: u64,
    #[serde(rename = "blockIds")]
    #[facet(rename = "blockIds")]
    block_ids: Vec<u64>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct WideStruct50 {
    field_00: u64,
    field_01: u64,
    field_02: u64,
    field_03: u64,
    field_04: u64,
    field_05: u64,
    field_06: u64,
    field_07: u64,
    field_08: u64,
    field_09: u64,
    field_10: String,
    field_11: String,
    field_12: String,
    field_13: String,
    field_14: String,
    field_15: String,
    field_16: String,
    field_17: String,
    field_18: String,
    field_19: String,
    field_20: f64,
    field_21: f64,
    field_22: f64,
    field_23: f64,
    field_24: f64,
    field_25: f64,
    field_26: f64,
    field_27: f64,
    field_28: f64,
    field_29: f64,
    field_30: bool,
    field_31: bool,
    field_32: bool,
    field_33: bool,
    field_34: bool,
    field_35: bool,
    field_36: bool,
    field_37: bool,
    field_38: bool,
    field_39: bool,
    field_40: i64,
    field_41: i64,
    field_42: i64,
    field_43: i64,
    field_44: i64,
    field_45: i64,
    field_46: i64,
    field_47: i64,
    field_48: i64,
    field_49: i64,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct WideStruct63 {
    // 50 required + 13 optional = 63 total fields (max for u64 bitmask)
    field_00: u64,
    field_01: u64,
    field_02: u64,
    field_03: u64,
    field_04: u64,
    field_05: u64,
    field_06: u64,
    field_07: u64,
    field_08: u64,
    field_09: u64,
    field_10: u64,
    field_11: u64,
    field_12: u64,
    field_13: u64,
    field_14: u64,
    field_15: u64,
    field_16: String,
    field_17: String,
    field_18: String,
    field_19: String,
    field_20: String,
    field_21: String,
    field_22: String,
    field_23: String,
    field_24: String,
    field_25: String,
    field_26: String,
    field_27: String,
    field_28: String,
    field_29: String,
    field_30: String,
    field_31: String,
    field_32: f64,
    field_33: f64,
    field_34: f64,
    field_35: f64,
    field_36: f64,
    field_37: f64,
    field_38: f64,
    field_39: f64,
    field_40: f64,
    field_41: f64,
    field_42: f64,
    field_43: f64,
    field_44: f64,
    field_45: f64,
    field_46: f64,
    field_47: f64,
    field_48: bool,
    field_49: bool,
    // Last 13 fields are optional to stay at 63 total fields (u64 bitmask limit)
    field_50: Option<bool>,
    field_51: Option<bool>,
    field_52: Option<bool>,
    field_53: Option<bool>,
    field_54: Option<bool>,
    field_55: Option<bool>,
    field_56: Option<bool>,
    field_57: Option<bool>,
    field_58: Option<i64>,
    field_59: Option<i64>,
    field_60: Option<i64>,
    field_61: Option<i64>,
    field_62: Option<i64>,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct SmallStruct {
    // Only 10 known fields - but JSON will have 50 total (40 unknown)
    id: u64,
    name: String,
    value: f64,
    active: bool,
    count: i64,
    score: f64,
    enabled: bool,
    index: u64,
    label: String,
    flag: bool,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Level1 {
    id: u64,
    data: String,
    nested: Level2,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Level2 {
    value: f64,
    flag: bool,
    nested: Level3,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Level3 {
    count: i64,
    name: String,
    nested: Level4,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Level4 {
    x: f64,
    y: f64,
    nested: Level5,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Level5 {
    leaf_id: u64,
    leaf_value: String,
    leaf_flag: bool,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct AuthPassword {
    password: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct AuthToken {
    token: String,
    token_expiry: u64,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
#[repr(C)]
enum AuthMethod {
    Password(AuthPassword),
    Token(AuthToken),
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct TransportTcp {
    tcp_port: u16,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct TransportUnix {
    socket_path: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
#[repr(C)]
enum Transport {
    Tcp(TransportTcp),
    Unix(TransportUnix),
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct StorageLocal {
    local_path: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct StorageRemote {
    remote_url: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
#[repr(C)]
enum Storage {
    Local(StorageLocal),
    Remote(StorageRemote),
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct LogFile {
    log_path: String,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct LogStdout {
    log_color: bool,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
#[repr(C)]
enum Logging {
    File(LogFile),
    Stdout(LogStdout),
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Config2Enums {
    name: String,
    #[facet(flatten)]
    #[serde(flatten)]
    auth: AuthMethod,
    #[facet(flatten)]
    #[serde(flatten)]
    transport: Transport,
}

#[derive(Debug, PartialEq, Facet, serde::Serialize, serde::Deserialize, Clone)]
struct Config4Enums {
    name: String,
    #[facet(flatten)]
    #[serde(flatten)]
    auth: AuthMethod,
    #[facet(flatten)]
    #[serde(flatten)]
    transport: Transport,
    #[facet(flatten)]
    #[serde(flatten)]
    storage: Storage,
    #[facet(flatten)]
    #[serde(flatten)]
    logging: Logging,
}
