packages:
  - "typescript/packages/*"
  - "typescript/subject"
  - "typescript/generated"
  - "typescript/tests/browser"
  - "typescript/tests/playwright"
  - "wasm/tests/browser-wasm"
  - "wasm/tests/browser-inprocess"
  - "wasm/tests/playwright"
