#[cfg(feature = "jit")]
use copypatch::extract::{Stencil, compile_object, extract_stencil};
#[cfg(feature = "jit")]
use std::{
    env, fs,
    path::{Path, PathBuf},
};

#[cfg(feature = "jit")]
const SYMBOLS: &[&str] = &["weavy_stencil_hostcall", "weavy_stencil_done"];

fn main() {
    #[cfg(feature = "jit")]
    {
        let out = PathBuf::from(env::var("OUT_DIR").unwrap());
        let generated = out.join("weavy_stencils.rs");
        let async_generated = out.join("weavy_async_stencils.rs");
        let task_generated = out.join("weavy_task_stencils.rs");
        let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

        if native_copy_patch_target(&target_os, &target_arch) {
            emit_native(&out, &generated);
            emit_async_native(&out, &async_generated);
            emit_task_native(&out, &task_generated);
        } else {
            emit_empty(&generated);
            emit_async_empty(&async_generated);
            emit_task_empty(&task_generated);
        }
    }
}

/// Async lane stencils: the suspend/resume substrate for the demand-driven
/// evaluator. Compiled with GUARANTEED tail calls (`become`, via
/// RUSTC_BOOTSTRAP on the stencil rustc only) so suspension is sound for
/// arbitrary-length chains — the whole chain runs in one driver-owned frame.
#[cfg(feature = "jit")]
const ASYNC_SYMBOLS: &[&str] = &[
    "weavy_async_push",
    "weavy_async_await",
    "weavy_async_add",
    "weavy_async_mul",
    "weavy_async_done",
];

#[cfg(feature = "jit")]
fn emit_async_empty(generated: &Path) {
    let mut s = String::new();
    for n in ["PUSH", "AWAIT", "ADD", "MUL", "DONE"] {
        s.push_str(&format!(
            "pub const {n}: &[u8] = &[];\npub const {n}_CONT: &[usize] = &[];\n"
        ));
    }
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit_async_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/async_ops.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_async_stencils.o");
    let src = Path::new("stencils/async_ops.rs");
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());

    // `become` needs `explicit_tail_calls`; RUSTC_BOOTSTRAP=1 unlocks it on the
    // stable toolchain for THIS spawned rustc only (never downstream crates).
    // At -O the bytes are identical to a plain call LLVM already TCOs; `become`
    // is the correctness guard that suspension can't silently regress.
    unsafe { env::set_var("RUSTC_BOOTSTRAP", "1") };
    let tailcall = compile_object(&rustc, &[], src, &obj, &target, true);
    if !tailcall {
        assert!(
            compile_object(&rustc, &[], src, &obj, &target, false),
            "rustc failed to compile Weavy async stencils"
        );
    }

    let bytes = fs::read(&obj).unwrap();
    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/async_ops.rs (async suspend lane).\n");
    for (name, sym) in [
        ("PUSH", "weavy_async_push"),
        ("AWAIT", "weavy_async_await"),
        ("ADD", "weavy_async_add"),
        ("MUL", "weavy_async_mul"),
        ("DONE", "weavy_async_done"),
    ] {
        let st = extract_stencil(&bytes, ASYNC_SYMBOLS, sym, "weavy_cont");
        emit(&mut s, name, &format!("`{sym}` async stencil."), &st);
        if name != "DONE" {
            emit_cont(&mut s, &format!("{name}_CONT"), name, &st);
        }
    }
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit_empty(generated: &Path) {
    fs::write(
        generated,
        "pub const HOSTCALL: &[u8] = &[];\n\
         pub const HOSTCALL_CONT: &[usize] = &[];\n\
         pub const DONE: &[u8] = &[];\n",
    )
    .unwrap();
}

#[cfg(feature = "jit")]
fn native_copy_patch_target(target_os: &str, target_arch: &str) -> bool {
    matches!(
        (target_os, target_arch),
        ("macos", "aarch64") | ("linux", "x86_64")
    )
}

#[cfg(feature = "jit")]
fn emit_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/hostcall.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_stencils.o");
    let src = Path::new("stencils/hostcall.rs");

    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    assert!(
        compile_object(&rustc, &[], src, &obj, &target, false),
        "rustc failed to compile Weavy stencils"
    );

    let bytes = fs::read(&obj).unwrap();
    let hostcall = extract_stencil(&bytes, SYMBOLS, "weavy_stencil_hostcall", "weavy_cont");
    let done = extract_stencil(&bytes, SYMBOLS, "weavy_stencil_done", "weavy_cont");

    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/hostcall.rs (rustc --emit=obj, call).\n");
    emit(
        &mut s,
        "HOSTCALL",
        "`weavy_stencil_hostcall`: call one consumer-provided intrinsic, continue.",
        &hostcall,
    );
    emit_cont(&mut s, "HOSTCALL_CONT", "HOSTCALL", &hostcall);
    emit(&mut s, "DONE", "`weavy_stencil_done`: a lone `ret`.", &done);
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit(out: &mut String, name: &str, doc: &str, stencil: &Stencil) {
    out.push_str(&format!(
        "/// {doc}\npub const {name}: &[u8] = &{:?};\n",
        stencil.bytes
    ));
}

#[cfg(feature = "jit")]
fn emit_cont(out: &mut String, name: &str, of: &str, stencil: &Stencil) {
    out.push_str(&format!(
        "/// Byte offsets within `{of}` of the continuation relocations to patch.\n\
         pub const {name}: &[usize] = &{:?};\n",
        stencil.cont_relocs
    ));
}

/// Task lane stencils: typed three-address ops over FRAME offsets (tooth 2 —
/// frames as declared records in per-task arenas; the ruled ABI). Same
/// guaranteed-tail-call discipline as the async lane.
#[cfg(feature = "jit")]
const TASK_SYMBOLS: &[&str] = &[
    "weavy_task_const",
    "weavy_task_add",
    "weavy_task_mul",
    "weavy_task_load_ix",
    "weavy_task_store_ix",
    "weavy_task_await",
    "weavy_task_call",
    "weavy_task_ret",
    "weavy_task_add_f64",
    "weavy_task_mul_f64",
    "weavy_task_hostcall",
    "weavy_task_trace",
    "weavy_task_done",
];

#[cfg(feature = "jit")]
const TASK_NAMES: &[(&str, &str)] = &[
    ("CONST", "weavy_task_const"),
    ("ADD", "weavy_task_add"),
    ("MUL", "weavy_task_mul"),
    ("LOAD_IX", "weavy_task_load_ix"),
    ("STORE_IX", "weavy_task_store_ix"),
    ("AWAIT", "weavy_task_await"),
    ("CALL", "weavy_task_call"),
    ("RET", "weavy_task_ret"),
    ("ADD_F64", "weavy_task_add_f64"),
    ("MUL_F64", "weavy_task_mul_f64"),
    ("HOSTCALL", "weavy_task_hostcall"),
    ("TRACE", "weavy_task_trace"),
    ("DONE", "weavy_task_done"),
];

#[cfg(feature = "jit")]
fn emit_task_empty(generated: &Path) {
    let mut s = String::new();
    for (n, _) in TASK_NAMES {
        s.push_str(&format!(
            "pub const {n}: &[u8] = &[];\npub const {n}_CONT: &[usize] = &[];\n"
        ));
    }
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit_task_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/task_ops.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_task_stencils.o");
    let src = Path::new("stencils/task_ops.rs");
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());

    unsafe { env::set_var("RUSTC_BOOTSTRAP", "1") };
    let tailcall = compile_object(&rustc, &[], src, &obj, &target, true);
    if !tailcall {
        assert!(
            compile_object(&rustc, &[], src, &obj, &target, false),
            "rustc failed to compile Weavy task stencils"
        );
    }

    let bytes = fs::read(&obj).unwrap();
    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/task_ops.rs (task frame lane).\n");
    for (name, sym) in TASK_NAMES {
        let st = extract_stencil(&bytes, TASK_SYMBOLS, sym, "weavy_cont");
        emit(&mut s, name, &format!("`{sym}` task stencil."), &st);
        emit_cont(&mut s, &format!("{name}_CONT"), name, &st);
    }
    fs::write(generated, s).unwrap();
}
