#[cfg(feature = "jit")]
use copypatch::extract::{Stencil, StencilN, compile_object, extract_stencil, extract_stencil_n};
use std::{
    env, fs,
    path::{Path, PathBuf},
};

#[path = "build/jit_config.rs"]
mod jit_config;

#[cfg(feature = "jit")]
const SYMBOLS: &[&str] = &["weavy_stencil_hostcall", "weavy_stencil_done"];

fn main() {
    println!("cargo::rustc-check-cfg=cfg(weavy_jit_active)");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=build/jit_config.rs");
    println!("cargo::rerun-if-env-changed=WEAVY_JIT");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated = out.join("weavy_stencils.rs");
    let async_generated = out.join("weavy_async_stencils.rs");
    let task_generated = out.join("weavy_task_stencils.rs");
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let feature_jit = env::var_os("CARGO_FEATURE_JIT").is_some();
    let policy_value = env::var("WEAVY_JIT").ok();
    let policy = jit_config::parse_policy(policy_value.as_deref()).unwrap_or_else(|err| {
        println!("cargo::error={err}");
        panic!("{err}");
    });

    if jit_config::jit_active(feature_jit, policy, &target_os, &target_arch) {
        println!("cargo::rustc-cfg=weavy_jit_active");
        println!("cargo::metadata=jit=1");
        emit_native(&out, &generated);
        emit_async_native(&out, &async_generated);
        emit_task_native(&out, &task_generated);
    } else {
        println!("cargo::metadata=jit=0");
        emit_empty(&generated);
        emit_async_empty(&async_generated);
        emit_task_empty(&task_generated);
    }
}

/// Async lane stencils: the suspend/resume substrate for the demand-driven
/// evaluator. Compiled with GUARANTEED tail calls (`become`, via
/// RUSTC_BOOTSTRAP on the stencil rustc only) so suspension is sound for
/// arbitrary-length chains — the whole chain runs in one driver-owned frame.
#[cfg(feature = "jit")]
const ASYNC_SYMBOLS: &[&str] = &[
    "weavy_async_push",
    "weavy_async_await",
    "weavy_async_add",
    "weavy_async_mul",
    "weavy_async_done",
];

fn emit_async_empty(generated: &Path) {
    let mut s = String::new();
    for n in ["PUSH", "AWAIT", "ADD", "MUL", "DONE"] {
        s.push_str(&format!(
            "pub const {n}: &[u8] = &[];\npub const {n}_CONT: &[usize] = &[];\n"
        ));
    }
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit_async_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/async_ops.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_async_stencils.o");
    let src = Path::new("stencils/async_ops.rs");
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());

    // `become` needs `explicit_tail_calls`; RUSTC_BOOTSTRAP=1 unlocks it on the
    // stable toolchain for THIS spawned rustc only (never downstream crates).
    // At -O the bytes are identical to a plain call LLVM already TCOs; `become`
    // is the correctness guard that suspension can't silently regress.
    unsafe { env::set_var("RUSTC_BOOTSTRAP", "1") };
    let tailcall = compile_object(&rustc, &[], src, &obj, &target, true);
    if !tailcall {
        assert!(
            compile_object(&rustc, &[], src, &obj, &target, false),
            "rustc failed to compile Weavy async stencils"
        );
    }

    let bytes = fs::read(&obj).unwrap();
    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/async_ops.rs (async suspend lane).\n");
    for (name, sym) in [
        ("PUSH", "weavy_async_push"),
        ("AWAIT", "weavy_async_await"),
        ("ADD", "weavy_async_add"),
        ("MUL", "weavy_async_mul"),
        ("DONE", "weavy_async_done"),
    ] {
        let st = extract_stencil(&bytes, ASYNC_SYMBOLS, sym, "weavy_cont");
        emit(&mut s, name, &format!("`{sym}` async stencil."), &st);
        if name != "DONE" {
            emit_cont(&mut s, &format!("{name}_CONT"), name, &st);
        }
    }
    fs::write(generated, s).unwrap();
}

#[cfg(not(feature = "jit"))]
fn emit_async_native(_: &Path, _: &Path) {
    unreachable!("Weavy native stencil extraction requires the jit feature")
}

fn emit_empty(generated: &Path) {
    fs::write(
        generated,
        "pub const HOSTCALL: &[u8] = &[];\n\
         pub const HOSTCALL_CONT: &[usize] = &[];\n\
         pub const DONE: &[u8] = &[];\n",
    )
    .unwrap();
}

#[cfg(feature = "jit")]
fn emit_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/hostcall.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_stencils.o");
    let src = Path::new("stencils/hostcall.rs");

    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    assert!(
        compile_object(&rustc, &[], src, &obj, &target, false),
        "rustc failed to compile Weavy stencils"
    );

    let bytes = fs::read(&obj).unwrap();
    let hostcall = extract_stencil(&bytes, SYMBOLS, "weavy_stencil_hostcall", "weavy_cont");
    let done = extract_stencil(&bytes, SYMBOLS, "weavy_stencil_done", "weavy_cont");

    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/hostcall.rs (rustc --emit=obj, call).\n");
    emit(
        &mut s,
        "HOSTCALL",
        "`weavy_stencil_hostcall`: call one consumer-provided intrinsic, continue.",
        &hostcall,
    );
    emit_cont(&mut s, "HOSTCALL_CONT", "HOSTCALL", &hostcall);
    emit(&mut s, "DONE", "`weavy_stencil_done`: a lone `ret`.", &done);
    fs::write(generated, s).unwrap();
}

#[cfg(not(feature = "jit"))]
fn emit_native(_: &Path, _: &Path) {
    unreachable!("Weavy native stencil extraction requires the jit feature")
}

#[cfg(feature = "jit")]
fn emit(out: &mut String, name: &str, doc: &str, stencil: &Stencil) {
    out.push_str(&format!(
        "/// {doc}\npub const {name}: &[u8] = &{:?};\n",
        stencil.bytes
    ));
}

#[cfg(feature = "jit")]
fn emit_cont(out: &mut String, name: &str, of: &str, stencil: &Stencil) {
    out.push_str(&format!(
        "/// Byte offsets within `{of}` of the continuation relocations to patch.\n\
         pub const {name}: &[usize] = &{:?};\n",
        stencil.cont_relocs
    ));
}

/// Task lane stencils: typed three-address ops over FRAME offsets (tooth 2 —
/// frames as declared records in per-task arenas; the ruled ABI). Same
/// guaranteed-tail-call discipline as the async lane.
#[cfg(feature = "jit")]
const TASK_SYMBOLS: &[&str] = &[
    "weavy_task_copy_value",
    "weavy_task_product_construct",
    "weavy_task_enum_construct",
    "weavy_task_enum_is_variant",
    "weavy_task_enum_project_checked",
    "weavy_task_const",
    "weavy_task_add",
    "weavy_task_mul",
    "weavy_task_sub",
    "weavy_task_div",
    "weavy_task_copy",
    "weavy_task_eq",
    "weavy_task_ne",
    "weavy_task_lt",
    "weavy_task_le",
    "weavy_task_gt",
    "weavy_task_ge",
    "weavy_task_jump",
    "weavy_task_jump_if_zero",
    "weavy_task_load_ix",
    "weavy_task_store_ix",
    "weavy_task_array_new",
    "weavy_task_ordered_empty",
    "weavy_task_ordered_begin_probe",
    "weavy_task_ordered_probe_key",
    "weavy_task_ordered_probe_value",
    "weavy_task_ordered_begin_insert",
    "weavy_task_ordered_insert_inspect",
    "weavy_task_ordered_insert_advance",
    "weavy_task_ordered_insert_commit",
    "weavy_task_ordered_begin_iterate",
    "weavy_task_ordered_iterate_row",
    "weavy_task_ordered_len",
    "weavy_task_ordered_status_is",
    "weavy_task_array_store_word",
    "weavy_task_load_array_word",
    "weavy_task_load_array",
    "weavy_task_load_array_len",
    "weavy_task_array_status_is",
    "weavy_task_compare_value_bytes",
    "weavy_task_string_concat",
    "weavy_task_string_contains",
    "weavy_task_string_is_numeric",
    "weavy_task_string_split_once",
    "weavy_task_string_parse_int",
    "weavy_task_string_status_is",
    "weavy_task_publish",
    "weavy_task_await",
    "weavy_task_call",
    "weavy_task_ret",
    "weavy_task_add_f64",
    "weavy_task_mul_f64",
    "weavy_task_hostcall",
    "weavy_task_hostcall_yield",
    "weavy_task_env_box",
    "weavy_task_env_load",
    "weavy_task_trace",
    "weavy_task_done",
];

const TASK_NAMES: &[(&str, &str)] = &[
    ("COPY_VALUE", "weavy_task_copy_value"),
    ("PRODUCT_CONSTRUCT", "weavy_task_product_construct"),
    ("ENUM_CONSTRUCT", "weavy_task_enum_construct"),
    ("ENUM_IS_VARIANT", "weavy_task_enum_is_variant"),
    ("ENUM_PROJECT_CHECKED", "weavy_task_enum_project_checked"),
    ("CONST", "weavy_task_const"),
    ("ADD", "weavy_task_add"),
    ("MUL", "weavy_task_mul"),
    ("SUB", "weavy_task_sub"),
    ("DIV", "weavy_task_div"),
    ("COPY", "weavy_task_copy"),
    ("EQ", "weavy_task_eq"),
    ("NE", "weavy_task_ne"),
    ("LT", "weavy_task_lt"),
    ("LE", "weavy_task_le"),
    ("GT", "weavy_task_gt"),
    ("GE", "weavy_task_ge"),
    ("JUMP", "weavy_task_jump"),
    ("JUMP_IF_ZERO", "weavy_task_jump_if_zero"),
    ("LOAD_IX", "weavy_task_load_ix"),
    ("STORE_IX", "weavy_task_store_ix"),
    ("ARRAY_NEW", "weavy_task_array_new"),
    ("ORDERED_EMPTY", "weavy_task_ordered_empty"),
    ("ORDERED_BEGIN_PROBE", "weavy_task_ordered_begin_probe"),
    ("ORDERED_PROBE_KEY", "weavy_task_ordered_probe_key"),
    ("ORDERED_PROBE_VALUE", "weavy_task_ordered_probe_value"),
    ("ORDERED_BEGIN_INSERT", "weavy_task_ordered_begin_insert"),
    (
        "ORDERED_INSERT_INSPECT",
        "weavy_task_ordered_insert_inspect",
    ),
    (
        "ORDERED_INSERT_ADVANCE",
        "weavy_task_ordered_insert_advance",
    ),
    ("ORDERED_INSERT_COMMIT", "weavy_task_ordered_insert_commit"),
    ("ORDERED_BEGIN_ITERATE", "weavy_task_ordered_begin_iterate"),
    ("ORDERED_ITERATE_ROW", "weavy_task_ordered_iterate_row"),
    ("ORDERED_LEN", "weavy_task_ordered_len"),
    ("ORDERED_STATUS_IS", "weavy_task_ordered_status_is"),
    ("ARRAY_STORE_WORD", "weavy_task_array_store_word"),
    ("LOAD_ARRAY_WORD", "weavy_task_load_array_word"),
    ("LOAD_ARRAY", "weavy_task_load_array"),
    ("LOAD_ARRAY_LEN", "weavy_task_load_array_len"),
    ("ARRAY_STATUS_IS", "weavy_task_array_status_is"),
    ("COMPARE_VALUE_BYTES", "weavy_task_compare_value_bytes"),
    ("STRING_CONCAT", "weavy_task_string_concat"),
    ("STRING_CONTAINS", "weavy_task_string_contains"),
    ("STRING_IS_NUMERIC", "weavy_task_string_is_numeric"),
    ("STRING_SPLIT_ONCE", "weavy_task_string_split_once"),
    ("STRING_PARSE_INT", "weavy_task_string_parse_int"),
    ("STRING_STATUS_IS", "weavy_task_string_status_is"),
    ("BYTE_PROJECT", "weavy_task_byte_project"),
    ("PATH_JOIN", "weavy_task_path_join"),
    ("PUBLISH", "weavy_task_publish"),
    ("AWAIT", "weavy_task_await"),
    ("CALL", "weavy_task_call"),
    ("RET", "weavy_task_ret"),
    ("ADD_F64", "weavy_task_add_f64"),
    ("MUL_F64", "weavy_task_mul_f64"),
    ("HOSTCALL", "weavy_task_hostcall"),
    ("HOSTCALL_YIELD", "weavy_task_hostcall_yield"),
    ("ENV_BOX", "weavy_task_env_box"),
    ("ENV_LOAD", "weavy_task_env_load"),
    ("TRACE", "weavy_task_trace"),
    ("DONE", "weavy_task_done"),
];

fn emit_task_empty(generated: &Path) {
    let mut s = String::new();
    for (n, _) in TASK_NAMES {
        s.push_str(&format!(
            "pub const {n}: &[u8] = &[];\npub const {n}_CONT: &[usize] = &[];\n"
        ));
    }
    s.push_str(
        "pub const JUMP_IF_ZERO_TAKEN_CONT: &[usize] = &[];\n\
         pub const JUMP_IF_ZERO_FALLTHROUGH_CONT: &[usize] = &[];\n",
    );
    fs::write(generated, s).unwrap();
}

#[cfg(feature = "jit")]
fn emit_task_native(out: &Path, generated: &Path) {
    println!("cargo:rerun-if-changed=stencils/task_ops.rs");

    let target = env::var("TARGET").expect("TARGET set by cargo");
    let obj = out.join("weavy_task_stencils.o");
    let src = Path::new("stencils/task_ops.rs");
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());

    unsafe { env::set_var("RUSTC_BOOTSTRAP", "1") };
    let tailcall = compile_object(&rustc, &[], src, &obj, &target, true);
    if !tailcall {
        assert!(
            compile_object(&rustc, &[], src, &obj, &target, false),
            "rustc failed to compile Weavy task stencils"
        );
    }

    let bytes = fs::read(&obj).unwrap();
    let mut s = String::new();
    s.push_str("// Generated by build.rs from stencils/task_ops.rs (task frame lane).\n");
    for (name, sym) in TASK_NAMES {
        if *name == "JUMP_IF_ZERO" {
            let st = extract_stencil_n(&bytes, TASK_SYMBOLS, sym, &["weavy_zero", "weavy_nonzero"]);
            emit_n(&mut s, name, &format!("`{sym}` task stencil."), &st);
            emit_cont_group(&mut s, "JUMP_IF_ZERO_TAKEN_CONT", name, &st.cont_relocs[0]);
            emit_cont_group(
                &mut s,
                "JUMP_IF_ZERO_FALLTHROUGH_CONT",
                name,
                &st.cont_relocs[1],
            );
        } else {
            let st = extract_stencil(&bytes, TASK_SYMBOLS, sym, "weavy_cont");
            emit(&mut s, name, &format!("`{sym}` task stencil."), &st);
            emit_cont(&mut s, &format!("{name}_CONT"), name, &st);
        }
    }
    fs::write(generated, s).unwrap();
}

#[cfg(not(feature = "jit"))]
fn emit_task_native(_: &Path, _: &Path) {
    unreachable!("Weavy native stencil extraction requires the jit feature")
}

#[cfg(feature = "jit")]
fn emit_n(out: &mut String, name: &str, doc: &str, stencil: &StencilN) {
    out.push_str(&format!(
        "/// {doc}\npub const {name}: &[u8] = &{:?};\n",
        stencil.bytes
    ));
}

#[cfg(feature = "jit")]
fn emit_cont_group(out: &mut String, name: &str, of: &str, relocs: &[usize]) {
    out.push_str(&format!(
        "/// Byte offsets within `{of}` of the continuation relocations to patch.\n\
         pub const {name}: &[usize] = &{relocs:?};\n",
    ));
}
