import PhonEngine
import PhonIR
import PhonSchema

public enum DibsSqlValue: Equatable {
    case null
    case bool(Bool)
    case i16(Int16)
    case i32(Int32)
    case i64(Int64)
    case f32(Float)
    case f64(Double)
    case string(String)
    case bytes([UInt8])
}

public struct DibsRowField: Equatable {
    var name: String
    var value: DibsSqlValue
}

public struct DibsColumnInfo: Equatable {
    var name: String
    var sqlType: String
    var rustType: String?
    var nullable: Bool
    var defaultValue: String?
    var primaryKey: Bool
    var unique: Bool
    var autoGenerated: Bool
    var long: Bool
    var label: Bool
    var enumVariants: [String]
    var doc: String?
    var lang: String?
    var icon: String?
    var subtype: String?
}

public struct DibsForeignKeyInfo: Equatable {
    var columns: [String]
    var referencesTable: String
    var referencesColumns: [String]
}

public struct DibsIndexColumnInfo: Equatable {
    var name: String
    var order: String
    var nulls: String
}

public struct DibsIndexInfo: Equatable {
    var name: String
    var columns: [DibsIndexColumnInfo]
    var unique: Bool
    var whereClause: String?
}

public struct DibsTableInfo: Equatable {
    var name: String
    var columns: [DibsColumnInfo]
    var foreignKeys: [DibsForeignKeyInfo]
    var indices: [DibsIndexInfo]
    var sourceFile: String?
    var sourceLine: UInt32?
    var doc: String?
    var icon: String?
}

public struct DibsSchemaInfo: Equatable {
    var tables: [DibsTableInfo]
}

public enum DibsFilterOp: Equatable {
    case eq
    case ne
    case lt
    case lte
    case gt
    case gte
    case like
    case iLike
    case isNull
    case isNotNull
    case `in`
    case jsonGet
    case jsonGetText
    case contains
    case keyExists
}

public struct DibsFilter: Equatable {
    var field: String
    var op: DibsFilterOp
    var value: DibsSqlValue
    var values: [DibsSqlValue]
}

public enum DibsSortDir: Equatable {
    case asc
    case desc
}

public struct DibsSort: Equatable {
    var field: String
    var dir: DibsSortDir
}

public struct DibsListRequest: Equatable {
    var table: String
    var filters: [DibsFilter]
    var sort: [DibsSort]
    var limit: UInt32?
    var offset: UInt32?
    var select: [String]
}

public struct DibsRow: Equatable {
    var fields: [DibsRowField]
}

public struct DibsServiceListResponse: Equatable {
    var rows: [DibsRow]
    var total: UInt64?
}

public struct DibsSqlError: Equatable {
    var message: String
    var sql: String?
    var position: UInt32?
    var hint: String?
    var detail: String?
    var caller: String?
}

public enum DibsError: Equatable {
    case connectionFailed(String)
    case migrationFailed(DibsSqlError)
    case invalidRequest(String)
    case unknownTable(String)
    case unknownColumn(String)
    case queryError(String)
}

public struct DibsGetRequest: Equatable {
    var table: String
    var pk: DibsSqlValue
}

public struct DibsCreateRequest: Equatable {
    var table: String
    var data: DibsRow
}

public struct DibsUpdateRequest: Equatable {
    var table: String
    var pk: DibsSqlValue
    var data: DibsRow
}

public struct DibsDeleteRequest: Equatable {
    var table: String
    var pk: DibsSqlValue
}

public enum DibsListResult: Equatable {
    case ok(DibsServiceListResponse)
    case err(DibsError)
}

public enum DibsGetResult: Equatable {
    case ok(DibsRow?)
    case err(DibsError)
}

public enum DibsRowResult: Equatable {
    case ok(DibsRow)
    case err(DibsError)
}

public enum DibsDeleteResult: Equatable {
    case ok(UInt64)
    case err(DibsError)
}

public struct DibsSquelServiceFixture: Equatable {
    var schema: DibsSchemaInfo
    var listRequest: DibsListRequest
    var listResponse: DibsListResult
    var getRequest: DibsGetRequest
    var getResponse: DibsGetResult
    var createRequest: DibsCreateRequest
    var createResponse: DibsRowResult
    var updateRequest: DibsUpdateRequest
    var updateResponse: DibsRowResult
    var deleteRequest: DibsDeleteRequest
    var deleteResponse: DibsDeleteResult
}

public struct DibsMigrationInfo: Equatable {
    var version: String
    var name: String
    var applied: Bool
    var appliedAt: String?
    var sourceFile: String?
    var source: String?
}

public struct DibsMigrationStatusRequest: Equatable {
    var databaseUrl: String
}

public struct DibsMigrateRequest: Equatable {
    var databaseUrl: String
    var migration: String?
}

public struct DibsAppliedMigration: Equatable {
    var version: String
    var appliedAt: String
}

public struct DibsRanMigration: Equatable {
    var version: String
    var durationMs: UInt64
}

public struct DibsMigrateResult: Equatable {
    var totalDefined: UInt32
    var alreadyApplied: [DibsAppliedMigration]
    var applied: [DibsRanMigration]
    var setupMs: UInt64
    var totalTimeMs: UInt64
}

public enum DibsMigrationStatusResult: Equatable {
    case ok([DibsMigrationInfo])
    case err(DibsError)
}

public enum DibsMigrateCallResult: Equatable {
    case ok(DibsMigrateResult)
    case err(DibsError)
}

public enum DibsLogLevel: Equatable {
    case debug
    case info
    case warn
    case error
}

public struct DibsMigrationLog: Equatable {
    var level: DibsLogLevel
    var message: String
    var migration: String?
}

public struct DibsMigrationServiceFixture: Equatable {
    var statusRequest: DibsMigrationStatusRequest
    var statusResponse: DibsMigrationStatusResult
    var migrateRequest: DibsMigrateRequest
    var migrateResponse: DibsMigrateCallResult
    var logItem: DibsMigrationLog
}

private enum DibsSchema {
    static let sqlValue = SchemaId(301)
    static let rowField = SchemaId(302)
    static let rowFieldList = SchemaId(303)
    static let optionString = SchemaId(304)
    static let stringList = SchemaId(305)
    static let optionU32 = SchemaId(306)
    static let optionU64 = SchemaId(307)
    static let listSqlValue = SchemaId(308)
    static let columnInfo = SchemaId(309)
    static let columnInfoList = SchemaId(310)
    static let foreignKeyInfo = SchemaId(311)
    static let foreignKeyInfoList = SchemaId(312)
    static let indexColumnInfo = SchemaId(313)
    static let indexColumnInfoList = SchemaId(314)
    static let indexInfo = SchemaId(315)
    static let indexInfoList = SchemaId(316)
    static let tableInfo = SchemaId(317)
    static let tableInfoList = SchemaId(318)
    static let schemaInfo = SchemaId(319)
    static let filterOp = SchemaId(320)
    static let filter = SchemaId(321)
    static let filterList = SchemaId(322)
    static let sortDir = SchemaId(323)
    static let sort = SchemaId(324)
    static let sortList = SchemaId(325)
    static let listRequest = SchemaId(326)
    static let row = SchemaId(327)
    static let rowList = SchemaId(328)
    static let serviceListResponse = SchemaId(329)
    static let sqlError = SchemaId(330)
    static let error = SchemaId(331)
    static let getRequest = SchemaId(332)
    static let createRequest = SchemaId(333)
    static let updateRequest = SchemaId(334)
    static let deleteRequest = SchemaId(335)
    static let listResult = SchemaId(336)
    static let optionRow = SchemaId(337)
    static let getResult = SchemaId(338)
    static let rowResult = SchemaId(339)
    static let deleteResult = SchemaId(340)
    static let squelServiceFixture = SchemaId(341)
    static let migrationInfo = SchemaId(342)
    static let migrationInfoList = SchemaId(343)
    static let migrationStatusRequest = SchemaId(344)
    static let migrateRequest = SchemaId(345)
    static let appliedMigration = SchemaId(346)
    static let appliedMigrationList = SchemaId(347)
    static let ranMigration = SchemaId(348)
    static let ranMigrationList = SchemaId(349)
    static let migrateResult = SchemaId(350)
    static let migrationStatusResult = SchemaId(351)
    static let migrateCallResult = SchemaId(352)
    static let logLevel = SchemaId(353)
    static let migrationLog = SchemaId(354)
    static let migrationServiceFixture = SchemaId(355)
}

private func scalarDesc(_ p: Primitive) -> Descriptor {
    let size = dibsFixedSize(p)!
    return Descriptor(
        schema: .concrete(primitiveId(p)),
        layout: Layout(size: size, align: dibsAlignment(p)),
        access: .scalar
    )
}

private func dibsFixedSize(_ p: Primitive) -> Int? {
    switch p {
    case .unit: return 0
    case .bool, .u8, .i8: return 1
    case .u16, .i16: return 2
    case .u32, .i32, .f32, .char: return 4
    case .u64, .i64, .f64: return 8
    case .u128, .i128: return 16
    case .string, .bytes, .never, .datetime, .uuid, .qname: return nil
    }
}

private func dibsAlignment(_ p: Primitive) -> Int {
    switch p {
    case .u16, .i16: return 2
    case .u32, .i32, .f32, .char: return 4
    case .u64, .i64, .f64: return 8
    case .u128, .i128: return 16
    default: return 1
    }
}

private func stringDesc() -> Descriptor {
    Descriptor(
        schema: .concrete(primitiveId(.string)),
        layout: MemoryLayout<String>.phonLayout,
        access: .bytes(BytesAccess(stride: 1, elemAlign: 1, witness: .string))
    )
}

private func bytesDesc() -> Descriptor {
    Descriptor(
        schema: .concrete(primitiveId(.bytes)),
        layout: MemoryLayout<[UInt8]>.phonLayout,
        access: .bytes(BytesAccess(stride: 1, elemAlign: 1, witness: .byteArray))
    )
}

private func optionDesc<Wrapped>(
    _ schema: SchemaId,
    _ type: Wrapped.Type,
    some: Descriptor
) -> Descriptor {
    Descriptor(
        schema: .concrete(schema),
        layout: MemoryLayout<Wrapped?>.phonLayout,
        access: .option(OptionAccess(witness: .of(Wrapped.self), some: some))
    )
}

private func listDesc<Element>(
    _ schema: SchemaId,
    _ type: Element.Type,
    element: Descriptor
) -> Descriptor {
    Descriptor(
        schema: .concrete(schema),
        layout: MemoryLayout<[Element]>.phonLayout,
        access: .sequence(SequenceAccess(
            element: element,
            stride: MemoryLayout<Element>.stride,
            elemAlign: MemoryLayout<Element>.alignment,
            witness: .of(Element.self)
        ))
    )
}

private func recordDesc<T>(
    _ schema: SchemaId,
    _ type: T.Type,
    fields: [FieldAccess]
) -> Descriptor {
    Descriptor(
        schema: .concrete(schema),
        layout: MemoryLayout<T>.phonLayout,
        access: .record(RecordAccess(fields: fields, construct: .inPlace))
    )
}

private func fieldAccess<Root, Field>(
    _ keyPath: KeyPath<Root, Field>,
    _ descriptor: Descriptor
) -> FieldAccess {
    FieldAccess(offset: MemoryLayout<Root>.offset(of: keyPath)!, descriptor: descriptor)
}

private func unitEnumDesc<T>(
    _ schema: SchemaId,
    _ type: T.Type,
    variantCount: Int,
    tag: @escaping (UnsafeRawPointer) -> Int,
    make: @escaping (Int) -> T
) -> Descriptor {
    Descriptor(
        schema: .concrete(schema),
        layout: MemoryLayout<T>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: { _, _, _ in },
            inject: { slot, localIndex, _ in
                slot.assumingMemoryBound(to: T.self).initialize(to: make(localIndex))
            },
            variants: (0 ..< variantCount).map { index in
                VariantAccess(wireIndex: UInt32(index), payloadFields: [], payloadLayout: Layout(size: 0, align: 1))
            }
        ))
    )
}

private func optionStringDesc() -> Descriptor {
    optionDesc(DibsSchema.optionString, String.self, some: stringDesc())
}

private func optionU32Desc() -> Descriptor {
    optionDesc(DibsSchema.optionU32, UInt32.self, some: scalarDesc(.u32))
}

private func optionU64Desc() -> Descriptor {
    optionDesc(DibsSchema.optionU64, UInt64.self, some: scalarDesc(.u64))
}

private func stringListDesc() -> Descriptor {
    listDesc(DibsSchema.stringList, String.self, element: stringDesc())
}

private func sqlValueDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsSqlValue.self).pointee {
        case .null: return 0
        case .bool: return 1
        case .i16: return 2
        case .i32: return 3
        case .i64: return 4
        case .f32: return 5
        case .f64: return 6
        case .string: return 7
        case .bytes: return 8
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsSqlValue.self).pointee {
        case .null:
            break
        case .bool(let payload):
            scratch.storeBytes(of: payload, as: Bool.self)
        case .i16(let payload):
            scratch.storeBytes(of: payload, as: Int16.self)
        case .i32(let payload):
            scratch.storeBytes(of: payload, as: Int32.self)
        case .i64(let payload):
            scratch.storeBytes(of: payload, as: Int64.self)
        case .f32(let payload):
            scratch.storeBytes(of: payload, as: Float.self)
        case .f64(let payload):
            scratch.storeBytes(of: payload, as: Double.self)
        case .string(let payload):
            scratch.assumingMemoryBound(to: String.self).initialize(to: payload)
        case .bytes(let payload):
            scratch.assumingMemoryBound(to: [UInt8].self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        switch localIndex {
        case 7:
            scratch.assumingMemoryBound(to: String.self).deinitialize(count: 1)
        case 8:
            scratch.assumingMemoryBound(to: [UInt8].self).deinitialize(count: 1)
        default:
            break
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsSqlValue
        switch localIndex {
        case 0:
            value = .null
        case 1:
            value = .bool(scratch.load(as: Bool.self))
        case 2:
            value = .i16(scratch.load(as: Int16.self))
        case 3:
            value = .i32(scratch.load(as: Int32.self))
        case 4:
            value = .i64(scratch.load(as: Int64.self))
        case 5:
            value = .f32(scratch.load(as: Float.self))
        case 6:
            value = .f64(scratch.load(as: Double.self))
        case 7:
            value = .string(scratch.assumingMemoryBound(to: String.self).move())
        case 8:
            value = .bytes(scratch.assumingMemoryBound(to: [UInt8].self).move())
        default:
            fatalError("bad DibsSqlValue variant index")
        }
        slot.assumingMemoryBound(to: DibsSqlValue.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.sqlValue),
        layout: MemoryLayout<DibsSqlValue>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [], payloadLayout: Layout(size: 0, align: 1)),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.bool))], payloadLayout: MemoryLayout<Bool>.phonLayout),
                VariantAccess(wireIndex: 2, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.i16))], payloadLayout: MemoryLayout<Int16>.phonLayout),
                VariantAccess(wireIndex: 3, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.i32))], payloadLayout: MemoryLayout<Int32>.phonLayout),
                VariantAccess(wireIndex: 4, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.i64))], payloadLayout: MemoryLayout<Int64>.phonLayout),
                VariantAccess(wireIndex: 5, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.f32))], payloadLayout: MemoryLayout<Float>.phonLayout),
                VariantAccess(wireIndex: 6, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.f64))], payloadLayout: MemoryLayout<Double>.phonLayout),
                VariantAccess(wireIndex: 7, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
                VariantAccess(wireIndex: 8, payloadFields: [FieldAccess(offset: 0, descriptor: bytesDesc())], payloadLayout: MemoryLayout<[UInt8]>.phonLayout),
            ]
        ))
    )
}

private func rowFieldDesc() -> Descriptor {
    recordDesc(DibsSchema.rowField, DibsRowField.self, fields: [
        fieldAccess(\DibsRowField.name, stringDesc()),
        fieldAccess(\DibsRowField.value, sqlValueDesc()),
    ])
}

private func rowFieldListDesc() -> Descriptor {
    listDesc(DibsSchema.rowFieldList, DibsRowField.self, element: rowFieldDesc())
}

private func sqlValueListDesc() -> Descriptor {
    listDesc(DibsSchema.listSqlValue, DibsSqlValue.self, element: sqlValueDesc())
}

private func columnInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.columnInfo, DibsColumnInfo.self, fields: [
        fieldAccess(\DibsColumnInfo.name, stringDesc()),
        fieldAccess(\DibsColumnInfo.sqlType, stringDesc()),
        fieldAccess(\DibsColumnInfo.rustType, optionStringDesc()),
        fieldAccess(\DibsColumnInfo.nullable, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.defaultValue, optionStringDesc()),
        fieldAccess(\DibsColumnInfo.primaryKey, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.unique, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.autoGenerated, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.long, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.label, scalarDesc(.bool)),
        fieldAccess(\DibsColumnInfo.enumVariants, stringListDesc()),
        fieldAccess(\DibsColumnInfo.doc, optionStringDesc()),
        fieldAccess(\DibsColumnInfo.lang, optionStringDesc()),
        fieldAccess(\DibsColumnInfo.icon, optionStringDesc()),
        fieldAccess(\DibsColumnInfo.subtype, optionStringDesc()),
    ])
}

private func columnInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.columnInfoList, DibsColumnInfo.self, element: columnInfoDesc())
}

private func foreignKeyInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.foreignKeyInfo, DibsForeignKeyInfo.self, fields: [
        fieldAccess(\DibsForeignKeyInfo.columns, stringListDesc()),
        fieldAccess(\DibsForeignKeyInfo.referencesTable, stringDesc()),
        fieldAccess(\DibsForeignKeyInfo.referencesColumns, stringListDesc()),
    ])
}

private func foreignKeyInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.foreignKeyInfoList, DibsForeignKeyInfo.self, element: foreignKeyInfoDesc())
}

private func indexColumnInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.indexColumnInfo, DibsIndexColumnInfo.self, fields: [
        fieldAccess(\DibsIndexColumnInfo.name, stringDesc()),
        fieldAccess(\DibsIndexColumnInfo.order, stringDesc()),
        fieldAccess(\DibsIndexColumnInfo.nulls, stringDesc()),
    ])
}

private func indexColumnInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.indexColumnInfoList, DibsIndexColumnInfo.self, element: indexColumnInfoDesc())
}

private func indexInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.indexInfo, DibsIndexInfo.self, fields: [
        fieldAccess(\DibsIndexInfo.name, stringDesc()),
        fieldAccess(\DibsIndexInfo.columns, indexColumnInfoListDesc()),
        fieldAccess(\DibsIndexInfo.unique, scalarDesc(.bool)),
        fieldAccess(\DibsIndexInfo.whereClause, optionStringDesc()),
    ])
}

private func indexInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.indexInfoList, DibsIndexInfo.self, element: indexInfoDesc())
}

private func tableInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.tableInfo, DibsTableInfo.self, fields: [
        fieldAccess(\DibsTableInfo.name, stringDesc()),
        fieldAccess(\DibsTableInfo.columns, columnInfoListDesc()),
        fieldAccess(\DibsTableInfo.foreignKeys, foreignKeyInfoListDesc()),
        fieldAccess(\DibsTableInfo.indices, indexInfoListDesc()),
        fieldAccess(\DibsTableInfo.sourceFile, optionStringDesc()),
        fieldAccess(\DibsTableInfo.sourceLine, optionU32Desc()),
        fieldAccess(\DibsTableInfo.doc, optionStringDesc()),
        fieldAccess(\DibsTableInfo.icon, optionStringDesc()),
    ])
}

private func tableInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.tableInfoList, DibsTableInfo.self, element: tableInfoDesc())
}

private func schemaInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.schemaInfo, DibsSchemaInfo.self, fields: [
        fieldAccess(\DibsSchemaInfo.tables, tableInfoListDesc()),
    ])
}

private func filterOpDesc() -> Descriptor {
    unitEnumDesc(
        DibsSchema.filterOp,
        DibsFilterOp.self,
        variantCount: 15,
        tag: { ptr in
            switch ptr.assumingMemoryBound(to: DibsFilterOp.self).pointee {
            case .eq: return 0
            case .ne: return 1
            case .lt: return 2
            case .lte: return 3
            case .gt: return 4
            case .gte: return 5
            case .like: return 6
            case .iLike: return 7
            case .isNull: return 8
            case .isNotNull: return 9
            case .in: return 10
            case .jsonGet: return 11
            case .jsonGetText: return 12
            case .contains: return 13
            case .keyExists: return 14
            }
        },
        make: { index in
            switch index {
            case 0: return .eq
            case 1: return .ne
            case 2: return .lt
            case 3: return .lte
            case 4: return .gt
            case 5: return .gte
            case 6: return .like
            case 7: return .iLike
            case 8: return .isNull
            case 9: return .isNotNull
            case 10: return .in
            case 11: return .jsonGet
            case 12: return .jsonGetText
            case 13: return .contains
            case 14: return .keyExists
            default: fatalError("bad DibsFilterOp variant index")
            }
        }
    )
}

private func filterDesc() -> Descriptor {
    recordDesc(DibsSchema.filter, DibsFilter.self, fields: [
        fieldAccess(\DibsFilter.field, stringDesc()),
        fieldAccess(\DibsFilter.op, filterOpDesc()),
        fieldAccess(\DibsFilter.value, sqlValueDesc()),
        fieldAccess(\DibsFilter.values, sqlValueListDesc()),
    ])
}

private func filterListDesc() -> Descriptor {
    listDesc(DibsSchema.filterList, DibsFilter.self, element: filterDesc())
}

private func sortDirDesc() -> Descriptor {
    unitEnumDesc(
        DibsSchema.sortDir,
        DibsSortDir.self,
        variantCount: 2,
        tag: { ptr in
            switch ptr.assumingMemoryBound(to: DibsSortDir.self).pointee {
            case .asc: return 0
            case .desc: return 1
            }
        },
        make: { index in
            switch index {
            case 0: return .asc
            case 1: return .desc
            default: fatalError("bad DibsSortDir variant index")
            }
        }
    )
}

private func sortDesc() -> Descriptor {
    recordDesc(DibsSchema.sort, DibsSort.self, fields: [
        fieldAccess(\DibsSort.field, stringDesc()),
        fieldAccess(\DibsSort.dir, sortDirDesc()),
    ])
}

private func sortListDesc() -> Descriptor {
    listDesc(DibsSchema.sortList, DibsSort.self, element: sortDesc())
}

private func listRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.listRequest, DibsListRequest.self, fields: [
        fieldAccess(\DibsListRequest.table, stringDesc()),
        fieldAccess(\DibsListRequest.filters, filterListDesc()),
        fieldAccess(\DibsListRequest.sort, sortListDesc()),
        fieldAccess(\DibsListRequest.limit, optionU32Desc()),
        fieldAccess(\DibsListRequest.offset, optionU32Desc()),
        fieldAccess(\DibsListRequest.select, stringListDesc()),
    ])
}

private func rowDesc() -> Descriptor {
    recordDesc(DibsSchema.row, DibsRow.self, fields: [
        fieldAccess(\DibsRow.fields, rowFieldListDesc()),
    ])
}

private func rowListDesc() -> Descriptor {
    listDesc(DibsSchema.rowList, DibsRow.self, element: rowDesc())
}

private func serviceListResponseDesc() -> Descriptor {
    recordDesc(DibsSchema.serviceListResponse, DibsServiceListResponse.self, fields: [
        fieldAccess(\DibsServiceListResponse.rows, rowListDesc()),
        fieldAccess(\DibsServiceListResponse.total, optionU64Desc()),
    ])
}

private func sqlErrorDesc() -> Descriptor {
    recordDesc(DibsSchema.sqlError, DibsSqlError.self, fields: [
        fieldAccess(\DibsSqlError.message, stringDesc()),
        fieldAccess(\DibsSqlError.sql, optionStringDesc()),
        fieldAccess(\DibsSqlError.position, optionU32Desc()),
        fieldAccess(\DibsSqlError.hint, optionStringDesc()),
        fieldAccess(\DibsSqlError.detail, optionStringDesc()),
        fieldAccess(\DibsSqlError.caller, optionStringDesc()),
    ])
}

private func errorDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsError.self).pointee {
        case .connectionFailed: return 0
        case .migrationFailed: return 1
        case .invalidRequest: return 2
        case .unknownTable: return 3
        case .unknownColumn: return 4
        case .queryError: return 5
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsError.self).pointee {
        case .connectionFailed(let payload),
             .invalidRequest(let payload),
             .unknownTable(let payload),
             .unknownColumn(let payload),
             .queryError(let payload):
            scratch.assumingMemoryBound(to: String.self).initialize(to: payload)
        case .migrationFailed(let payload):
            scratch.assumingMemoryBound(to: DibsSqlError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        switch localIndex {
        case 1:
            scratch.assumingMemoryBound(to: DibsSqlError.self).deinitialize(count: 1)
        default:
            scratch.assumingMemoryBound(to: String.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsError
        switch localIndex {
        case 0:
            value = .connectionFailed(scratch.assumingMemoryBound(to: String.self).move())
        case 1:
            value = .migrationFailed(scratch.assumingMemoryBound(to: DibsSqlError.self).move())
        case 2:
            value = .invalidRequest(scratch.assumingMemoryBound(to: String.self).move())
        case 3:
            value = .unknownTable(scratch.assumingMemoryBound(to: String.self).move())
        case 4:
            value = .unknownColumn(scratch.assumingMemoryBound(to: String.self).move())
        case 5:
            value = .queryError(scratch.assumingMemoryBound(to: String.self).move())
        default:
            fatalError("bad DibsError variant index")
        }
        slot.assumingMemoryBound(to: DibsError.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.error),
        layout: MemoryLayout<DibsError>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: sqlErrorDesc())], payloadLayout: MemoryLayout<DibsSqlError>.phonLayout),
                VariantAccess(wireIndex: 2, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
                VariantAccess(wireIndex: 3, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
                VariantAccess(wireIndex: 4, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
                VariantAccess(wireIndex: 5, payloadFields: [FieldAccess(offset: 0, descriptor: stringDesc())], payloadLayout: MemoryLayout<String>.phonLayout),
            ]
        ))
    )
}

private func getRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.getRequest, DibsGetRequest.self, fields: [
        fieldAccess(\DibsGetRequest.table, stringDesc()),
        fieldAccess(\DibsGetRequest.pk, sqlValueDesc()),
    ])
}

private func createRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.createRequest, DibsCreateRequest.self, fields: [
        fieldAccess(\DibsCreateRequest.table, stringDesc()),
        fieldAccess(\DibsCreateRequest.data, rowDesc()),
    ])
}

private func updateRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.updateRequest, DibsUpdateRequest.self, fields: [
        fieldAccess(\DibsUpdateRequest.table, stringDesc()),
        fieldAccess(\DibsUpdateRequest.pk, sqlValueDesc()),
        fieldAccess(\DibsUpdateRequest.data, rowDesc()),
    ])
}

private func deleteRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.deleteRequest, DibsDeleteRequest.self, fields: [
        fieldAccess(\DibsDeleteRequest.table, stringDesc()),
        fieldAccess(\DibsDeleteRequest.pk, sqlValueDesc()),
    ])
}

private func optionRowDesc() -> Descriptor {
    optionDesc(DibsSchema.optionRow, DibsRow.self, some: rowDesc())
}

private func listResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsListResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsListResult.self).pointee {
        case .ok(let payload):
            scratch.assumingMemoryBound(to: DibsServiceListResponse.self).initialize(to: payload)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 0 {
            scratch.assumingMemoryBound(to: DibsServiceListResponse.self).deinitialize(count: 1)
        } else {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsListResult
        if localIndex == 0 {
            value = .ok(scratch.assumingMemoryBound(to: DibsServiceListResponse.self).move())
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsListResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.listResult),
        layout: MemoryLayout<DibsListResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: serviceListResponseDesc())], payloadLayout: MemoryLayout<DibsServiceListResponse>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func getResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsGetResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsGetResult.self).pointee {
        case .ok(let payload):
            scratch.assumingMemoryBound(to: DibsRow?.self).initialize(to: payload)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 0 {
            scratch.assumingMemoryBound(to: DibsRow?.self).deinitialize(count: 1)
        } else {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsGetResult
        if localIndex == 0 {
            value = .ok(scratch.assumingMemoryBound(to: DibsRow?.self).move())
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsGetResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.getResult),
        layout: MemoryLayout<DibsGetResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: optionRowDesc())], payloadLayout: MemoryLayout<DibsRow?>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func rowResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsRowResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsRowResult.self).pointee {
        case .ok(let payload):
            scratch.assumingMemoryBound(to: DibsRow.self).initialize(to: payload)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 0 {
            scratch.assumingMemoryBound(to: DibsRow.self).deinitialize(count: 1)
        } else {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsRowResult
        if localIndex == 0 {
            value = .ok(scratch.assumingMemoryBound(to: DibsRow.self).move())
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsRowResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.rowResult),
        layout: MemoryLayout<DibsRowResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: rowDesc())], payloadLayout: MemoryLayout<DibsRow>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func deleteResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsDeleteResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsDeleteResult.self).pointee {
        case .ok(let payload):
            scratch.storeBytes(of: payload, as: UInt64.self)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 1 {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsDeleteResult
        if localIndex == 0 {
            value = .ok(scratch.load(as: UInt64.self))
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsDeleteResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.deleteResult),
        layout: MemoryLayout<DibsDeleteResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: scalarDesc(.u64))], payloadLayout: MemoryLayout<UInt64>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func migrationInfoDesc() -> Descriptor {
    recordDesc(DibsSchema.migrationInfo, DibsMigrationInfo.self, fields: [
        fieldAccess(\DibsMigrationInfo.version, stringDesc()),
        fieldAccess(\DibsMigrationInfo.name, stringDesc()),
        fieldAccess(\DibsMigrationInfo.applied, scalarDesc(.bool)),
        fieldAccess(\DibsMigrationInfo.appliedAt, optionStringDesc()),
        fieldAccess(\DibsMigrationInfo.sourceFile, optionStringDesc()),
        fieldAccess(\DibsMigrationInfo.source, optionStringDesc()),
    ])
}

private func migrationInfoListDesc() -> Descriptor {
    listDesc(DibsSchema.migrationInfoList, DibsMigrationInfo.self, element: migrationInfoDesc())
}

private func migrationStatusRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.migrationStatusRequest, DibsMigrationStatusRequest.self, fields: [
        fieldAccess(\DibsMigrationStatusRequest.databaseUrl, stringDesc()),
    ])
}

private func migrateRequestDesc() -> Descriptor {
    recordDesc(DibsSchema.migrateRequest, DibsMigrateRequest.self, fields: [
        fieldAccess(\DibsMigrateRequest.databaseUrl, stringDesc()),
        fieldAccess(\DibsMigrateRequest.migration, optionStringDesc()),
    ])
}

private func appliedMigrationDesc() -> Descriptor {
    recordDesc(DibsSchema.appliedMigration, DibsAppliedMigration.self, fields: [
        fieldAccess(\DibsAppliedMigration.version, stringDesc()),
        fieldAccess(\DibsAppliedMigration.appliedAt, stringDesc()),
    ])
}

private func appliedMigrationListDesc() -> Descriptor {
    listDesc(DibsSchema.appliedMigrationList, DibsAppliedMigration.self, element: appliedMigrationDesc())
}

private func ranMigrationDesc() -> Descriptor {
    recordDesc(DibsSchema.ranMigration, DibsRanMigration.self, fields: [
        fieldAccess(\DibsRanMigration.version, stringDesc()),
        fieldAccess(\DibsRanMigration.durationMs, scalarDesc(.u64)),
    ])
}

private func ranMigrationListDesc() -> Descriptor {
    listDesc(DibsSchema.ranMigrationList, DibsRanMigration.self, element: ranMigrationDesc())
}

private func migrateResultDesc() -> Descriptor {
    recordDesc(DibsSchema.migrateResult, DibsMigrateResult.self, fields: [
        fieldAccess(\DibsMigrateResult.totalDefined, scalarDesc(.u32)),
        fieldAccess(\DibsMigrateResult.alreadyApplied, appliedMigrationListDesc()),
        fieldAccess(\DibsMigrateResult.applied, ranMigrationListDesc()),
        fieldAccess(\DibsMigrateResult.setupMs, scalarDesc(.u64)),
        fieldAccess(\DibsMigrateResult.totalTimeMs, scalarDesc(.u64)),
    ])
}

private func migrationStatusResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsMigrationStatusResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsMigrationStatusResult.self).pointee {
        case .ok(let payload):
            scratch.assumingMemoryBound(to: [DibsMigrationInfo].self).initialize(to: payload)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 0 {
            scratch.assumingMemoryBound(to: [DibsMigrationInfo].self).deinitialize(count: 1)
        } else {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsMigrationStatusResult
        if localIndex == 0 {
            value = .ok(scratch.assumingMemoryBound(to: [DibsMigrationInfo].self).move())
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsMigrationStatusResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.migrationStatusResult),
        layout: MemoryLayout<DibsMigrationStatusResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: migrationInfoListDesc())], payloadLayout: MemoryLayout<[DibsMigrationInfo]>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func migrateCallResultDesc() -> Descriptor {
    let tag: (UnsafeRawPointer) -> Int = { ptr in
        switch ptr.assumingMemoryBound(to: DibsMigrateCallResult.self).pointee {
        case .ok: return 0
        case .err: return 1
        }
    }
    let projectPayload: (UnsafeRawPointer, Int, UnsafeMutableRawPointer) -> Void = { value, _, scratch in
        switch value.assumingMemoryBound(to: DibsMigrateCallResult.self).pointee {
        case .ok(let payload):
            scratch.assumingMemoryBound(to: DibsMigrateResult.self).initialize(to: payload)
        case .err(let payload):
            scratch.assumingMemoryBound(to: DibsError.self).initialize(to: payload)
        }
    }
    let destroyPayload: (UnsafeMutableRawPointer, Int) -> Void = { scratch, localIndex in
        if localIndex == 0 {
            scratch.assumingMemoryBound(to: DibsMigrateResult.self).deinitialize(count: 1)
        } else {
            scratch.assumingMemoryBound(to: DibsError.self).deinitialize(count: 1)
        }
    }
    let inject: (UnsafeMutableRawPointer, Int, UnsafeMutableRawPointer) -> Void = { slot, localIndex, scratch in
        let value: DibsMigrateCallResult
        if localIndex == 0 {
            value = .ok(scratch.assumingMemoryBound(to: DibsMigrateResult.self).move())
        } else {
            value = .err(scratch.assumingMemoryBound(to: DibsError.self).move())
        }
        slot.assumingMemoryBound(to: DibsMigrateCallResult.self).initialize(to: value)
    }

    return Descriptor(
        schema: .concrete(DibsSchema.migrateCallResult),
        layout: MemoryLayout<DibsMigrateCallResult>.phonLayout,
        access: .enumeration(EnumAccess(
            tag: tag,
            projectPayload: projectPayload,
            destroyPayload: destroyPayload,
            inject: inject,
            variants: [
                VariantAccess(wireIndex: 0, payloadFields: [FieldAccess(offset: 0, descriptor: migrateResultDesc())], payloadLayout: MemoryLayout<DibsMigrateResult>.phonLayout),
                VariantAccess(wireIndex: 1, payloadFields: [FieldAccess(offset: 0, descriptor: errorDesc())], payloadLayout: MemoryLayout<DibsError>.phonLayout),
            ]
        ))
    )
}

private func logLevelDesc() -> Descriptor {
    unitEnumDesc(
        DibsSchema.logLevel,
        DibsLogLevel.self,
        variantCount: 4,
        tag: { ptr in
            switch ptr.assumingMemoryBound(to: DibsLogLevel.self).pointee {
            case .debug: return 0
            case .info: return 1
            case .warn: return 2
            case .error: return 3
            }
        },
        make: { index in
            switch index {
            case 0: return .debug
            case 1: return .info
            case 2: return .warn
            case 3: return .error
            default: fatalError("bad DibsLogLevel variant index")
            }
        }
    )
}

private func migrationLogDesc() -> Descriptor {
    recordDesc(DibsSchema.migrationLog, DibsMigrationLog.self, fields: [
        fieldAccess(\DibsMigrationLog.level, logLevelDesc()),
        fieldAccess(\DibsMigrationLog.message, stringDesc()),
        fieldAccess(\DibsMigrationLog.migration, optionStringDesc()),
    ])
}

private func migrationServiceFixtureDesc() -> Descriptor {
    recordDesc(DibsSchema.migrationServiceFixture, DibsMigrationServiceFixture.self, fields: [
        fieldAccess(\DibsMigrationServiceFixture.statusRequest, migrationStatusRequestDesc()),
        fieldAccess(\DibsMigrationServiceFixture.statusResponse, migrationStatusResultDesc()),
        fieldAccess(\DibsMigrationServiceFixture.migrateRequest, migrateRequestDesc()),
        fieldAccess(\DibsMigrationServiceFixture.migrateResponse, migrateCallResultDesc()),
        fieldAccess(\DibsMigrationServiceFixture.logItem, migrationLogDesc()),
    ])
}

private func dibsSchemas() -> [Schema] {
    [
        Schema(id: DibsSchema.optionString, kind: .option(element: .concrete(primitiveId(.string)))),
        Schema(id: DibsSchema.optionU32, kind: .option(element: .concrete(primitiveId(.u32)))),
        Schema(id: DibsSchema.optionU64, kind: .option(element: .concrete(primitiveId(.u64)))),
        Schema(id: DibsSchema.stringList, kind: .list(element: .concrete(primitiveId(.string)))),
        Schema(id: DibsSchema.sqlValue, kind: .enumeration(name: "SqlValue", variants: [
            Variant(name: "Null", index: 0, payload: .unit),
            Variant(name: "Bool", index: 1, payload: .newtype(.concrete(primitiveId(.bool)))),
            Variant(name: "I16", index: 2, payload: .newtype(.concrete(primitiveId(.i16)))),
            Variant(name: "I32", index: 3, payload: .newtype(.concrete(primitiveId(.i32)))),
            Variant(name: "I64", index: 4, payload: .newtype(.concrete(primitiveId(.i64)))),
            Variant(name: "F32", index: 5, payload: .newtype(.concrete(primitiveId(.f32)))),
            Variant(name: "F64", index: 6, payload: .newtype(.concrete(primitiveId(.f64)))),
            Variant(name: "String", index: 7, payload: .newtype(.concrete(primitiveId(.string)))),
            Variant(name: "Bytes", index: 8, payload: .newtype(.concrete(primitiveId(.bytes)))),
        ])),
        Schema(id: DibsSchema.rowField, kind: .structure(name: "RowField", fields: [
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "value", schema: .concrete(DibsSchema.sqlValue), required: true),
        ])),
        Schema(id: DibsSchema.rowFieldList, kind: .list(element: .concrete(DibsSchema.rowField))),
        Schema(id: DibsSchema.listSqlValue, kind: .list(element: .concrete(DibsSchema.sqlValue))),
        Schema(id: DibsSchema.columnInfo, kind: .structure(name: "DibsColumnInfo", fields: [
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "sql_type", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "rust_type", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "nullable", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "default", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "primary_key", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "unique", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "auto_generated", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "long", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "label", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "enum_variants", schema: .concrete(DibsSchema.stringList), required: true),
            Field(name: "doc", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "lang", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "icon", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "subtype", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.columnInfoList, kind: .list(element: .concrete(DibsSchema.columnInfo))),
        Schema(id: DibsSchema.foreignKeyInfo, kind: .structure(name: "DibsForeignKeyInfo", fields: [
            Field(name: "columns", schema: .concrete(DibsSchema.stringList), required: true),
            Field(name: "references_table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "references_columns", schema: .concrete(DibsSchema.stringList), required: true),
        ])),
        Schema(id: DibsSchema.foreignKeyInfoList, kind: .list(element: .concrete(DibsSchema.foreignKeyInfo))),
        Schema(id: DibsSchema.indexColumnInfo, kind: .structure(name: "DibsIndexColumnInfo", fields: [
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "order", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "nulls", schema: .concrete(primitiveId(.string)), required: true),
        ])),
        Schema(id: DibsSchema.indexColumnInfoList, kind: .list(element: .concrete(DibsSchema.indexColumnInfo))),
        Schema(id: DibsSchema.indexInfo, kind: .structure(name: "DibsIndexInfo", fields: [
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "columns", schema: .concrete(DibsSchema.indexColumnInfoList), required: true),
            Field(name: "unique", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "where_clause", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.indexInfoList, kind: .list(element: .concrete(DibsSchema.indexInfo))),
        Schema(id: DibsSchema.tableInfo, kind: .structure(name: "DibsTableInfo", fields: [
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "columns", schema: .concrete(DibsSchema.columnInfoList), required: true),
            Field(name: "foreign_keys", schema: .concrete(DibsSchema.foreignKeyInfoList), required: true),
            Field(name: "indices", schema: .concrete(DibsSchema.indexInfoList), required: true),
            Field(name: "source_file", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "source_line", schema: .concrete(DibsSchema.optionU32), required: true),
            Field(name: "doc", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "icon", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.tableInfoList, kind: .list(element: .concrete(DibsSchema.tableInfo))),
        Schema(id: DibsSchema.schemaInfo, kind: .structure(name: "DibsSchemaInfo", fields: [
            Field(name: "tables", schema: .concrete(DibsSchema.tableInfoList), required: true),
        ])),
        Schema(id: DibsSchema.filterOp, kind: .enumeration(name: "DibsFilterOp", variants: [
            Variant(name: "Eq", index: 0, payload: .unit),
            Variant(name: "Ne", index: 1, payload: .unit),
            Variant(name: "Lt", index: 2, payload: .unit),
            Variant(name: "Lte", index: 3, payload: .unit),
            Variant(name: "Gt", index: 4, payload: .unit),
            Variant(name: "Gte", index: 5, payload: .unit),
            Variant(name: "Like", index: 6, payload: .unit),
            Variant(name: "ILike", index: 7, payload: .unit),
            Variant(name: "IsNull", index: 8, payload: .unit),
            Variant(name: "IsNotNull", index: 9, payload: .unit),
            Variant(name: "In", index: 10, payload: .unit),
            Variant(name: "JsonGet", index: 11, payload: .unit),
            Variant(name: "JsonGetText", index: 12, payload: .unit),
            Variant(name: "Contains", index: 13, payload: .unit),
            Variant(name: "KeyExists", index: 14, payload: .unit),
        ])),
        Schema(id: DibsSchema.filter, kind: .structure(name: "DibsFilter", fields: [
            Field(name: "field", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "op", schema: .concrete(DibsSchema.filterOp), required: true),
            Field(name: "value", schema: .concrete(DibsSchema.sqlValue), required: true),
            Field(name: "values", schema: .concrete(DibsSchema.listSqlValue), required: true),
        ])),
        Schema(id: DibsSchema.filterList, kind: .list(element: .concrete(DibsSchema.filter))),
        Schema(id: DibsSchema.sortDir, kind: .enumeration(name: "DibsSortDir", variants: [
            Variant(name: "Asc", index: 0, payload: .unit),
            Variant(name: "Desc", index: 1, payload: .unit),
        ])),
        Schema(id: DibsSchema.sort, kind: .structure(name: "DibsSort", fields: [
            Field(name: "field", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "dir", schema: .concrete(DibsSchema.sortDir), required: true),
        ])),
        Schema(id: DibsSchema.sortList, kind: .list(element: .concrete(DibsSchema.sort))),
        Schema(id: DibsSchema.listRequest, kind: .structure(name: "DibsListRequest", fields: [
            Field(name: "table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "filters", schema: .concrete(DibsSchema.filterList), required: true),
            Field(name: "sort", schema: .concrete(DibsSchema.sortList), required: true),
            Field(name: "limit", schema: .concrete(DibsSchema.optionU32), required: true),
            Field(name: "offset", schema: .concrete(DibsSchema.optionU32), required: true),
            Field(name: "select", schema: .concrete(DibsSchema.stringList), required: true),
        ])),
        Schema(id: DibsSchema.row, kind: .structure(name: "DibsRow", fields: [
            Field(name: "fields", schema: .concrete(DibsSchema.rowFieldList), required: true),
        ])),
        Schema(id: DibsSchema.rowList, kind: .list(element: .concrete(DibsSchema.row))),
        Schema(id: DibsSchema.serviceListResponse, kind: .structure(name: "DibsServiceListResponse", fields: [
            Field(name: "rows", schema: .concrete(DibsSchema.rowList), required: true),
            Field(name: "total", schema: .concrete(DibsSchema.optionU64), required: true),
        ])),
        Schema(id: DibsSchema.sqlError, kind: .structure(name: "DibsSqlError", fields: [
            Field(name: "message", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "sql", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "position", schema: .concrete(DibsSchema.optionU32), required: true),
            Field(name: "hint", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "detail", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "caller", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.error, kind: .enumeration(name: "DibsError", variants: [
            Variant(name: "ConnectionFailed", index: 0, payload: .newtype(.concrete(primitiveId(.string)))),
            Variant(name: "MigrationFailed", index: 1, payload: .newtype(.concrete(DibsSchema.sqlError))),
            Variant(name: "InvalidRequest", index: 2, payload: .newtype(.concrete(primitiveId(.string)))),
            Variant(name: "UnknownTable", index: 3, payload: .newtype(.concrete(primitiveId(.string)))),
            Variant(name: "UnknownColumn", index: 4, payload: .newtype(.concrete(primitiveId(.string)))),
            Variant(name: "QueryError", index: 5, payload: .newtype(.concrete(primitiveId(.string)))),
        ])),
        Schema(id: DibsSchema.getRequest, kind: .structure(name: "DibsGetRequest", fields: [
            Field(name: "table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "pk", schema: .concrete(DibsSchema.sqlValue), required: true),
        ])),
        Schema(id: DibsSchema.createRequest, kind: .structure(name: "DibsCreateRequest", fields: [
            Field(name: "table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "data", schema: .concrete(DibsSchema.row), required: true),
        ])),
        Schema(id: DibsSchema.updateRequest, kind: .structure(name: "DibsUpdateRequest", fields: [
            Field(name: "table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "pk", schema: .concrete(DibsSchema.sqlValue), required: true),
            Field(name: "data", schema: .concrete(DibsSchema.row), required: true),
        ])),
        Schema(id: DibsSchema.deleteRequest, kind: .structure(name: "DibsDeleteRequest", fields: [
            Field(name: "table", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "pk", schema: .concrete(DibsSchema.sqlValue), required: true),
        ])),
        Schema(id: DibsSchema.listResult, kind: .enumeration(name: "DibsListResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(DibsSchema.serviceListResponse))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.optionRow, kind: .option(element: .concrete(DibsSchema.row))),
        Schema(id: DibsSchema.getResult, kind: .enumeration(name: "DibsGetResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(DibsSchema.optionRow))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.rowResult, kind: .enumeration(name: "DibsRowResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(DibsSchema.row))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.deleteResult, kind: .enumeration(name: "DibsDeleteResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(primitiveId(.u64)))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.squelServiceFixture, kind: .structure(name: "DibsSquelServiceFixture", fields: [
            Field(name: "schema", schema: .concrete(DibsSchema.schemaInfo), required: true),
            Field(name: "list_request", schema: .concrete(DibsSchema.listRequest), required: true),
            Field(name: "list_response", schema: .concrete(DibsSchema.listResult), required: true),
            Field(name: "get_request", schema: .concrete(DibsSchema.getRequest), required: true),
            Field(name: "get_response", schema: .concrete(DibsSchema.getResult), required: true),
            Field(name: "create_request", schema: .concrete(DibsSchema.createRequest), required: true),
            Field(name: "create_response", schema: .concrete(DibsSchema.rowResult), required: true),
            Field(name: "update_request", schema: .concrete(DibsSchema.updateRequest), required: true),
            Field(name: "update_response", schema: .concrete(DibsSchema.rowResult), required: true),
            Field(name: "delete_request", schema: .concrete(DibsSchema.deleteRequest), required: true),
            Field(name: "delete_response", schema: .concrete(DibsSchema.deleteResult), required: true),
        ])),
        Schema(id: DibsSchema.migrationInfo, kind: .structure(name: "DibsMigrationInfo", fields: [
            Field(name: "version", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "name", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "applied", schema: .concrete(primitiveId(.bool)), required: true),
            Field(name: "applied_at", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "source_file", schema: .concrete(DibsSchema.optionString), required: true),
            Field(name: "source", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.migrationInfoList, kind: .list(element: .concrete(DibsSchema.migrationInfo))),
        Schema(id: DibsSchema.migrationStatusRequest, kind: .structure(name: "DibsMigrationStatusRequest", fields: [
            Field(name: "database_url", schema: .concrete(primitiveId(.string)), required: true),
        ])),
        Schema(id: DibsSchema.migrateRequest, kind: .structure(name: "DibsMigrateRequest", fields: [
            Field(name: "database_url", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "migration", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.appliedMigration, kind: .structure(name: "DibsAppliedMigration", fields: [
            Field(name: "version", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "applied_at", schema: .concrete(primitiveId(.string)), required: true),
        ])),
        Schema(id: DibsSchema.appliedMigrationList, kind: .list(element: .concrete(DibsSchema.appliedMigration))),
        Schema(id: DibsSchema.ranMigration, kind: .structure(name: "DibsRanMigration", fields: [
            Field(name: "version", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "duration_ms", schema: .concrete(primitiveId(.u64)), required: true),
        ])),
        Schema(id: DibsSchema.ranMigrationList, kind: .list(element: .concrete(DibsSchema.ranMigration))),
        Schema(id: DibsSchema.migrateResult, kind: .structure(name: "DibsMigrateResult", fields: [
            Field(name: "total_defined", schema: .concrete(primitiveId(.u32)), required: true),
            Field(name: "already_applied", schema: .concrete(DibsSchema.appliedMigrationList), required: true),
            Field(name: "applied", schema: .concrete(DibsSchema.ranMigrationList), required: true),
            Field(name: "setup_ms", schema: .concrete(primitiveId(.u64)), required: true),
            Field(name: "total_time_ms", schema: .concrete(primitiveId(.u64)), required: true),
        ])),
        Schema(id: DibsSchema.migrationStatusResult, kind: .enumeration(name: "DibsMigrationStatusResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(DibsSchema.migrationInfoList))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.migrateCallResult, kind: .enumeration(name: "DibsMigrateCallResult", variants: [
            Variant(name: "Ok", index: 0, payload: .newtype(.concrete(DibsSchema.migrateResult))),
            Variant(name: "Err", index: 1, payload: .newtype(.concrete(DibsSchema.error))),
        ])),
        Schema(id: DibsSchema.logLevel, kind: .enumeration(name: "DibsLogLevel", variants: [
            Variant(name: "Debug", index: 0, payload: .unit),
            Variant(name: "Info", index: 1, payload: .unit),
            Variant(name: "Warn", index: 2, payload: .unit),
            Variant(name: "Error", index: 3, payload: .unit),
        ])),
        Schema(id: DibsSchema.migrationLog, kind: .structure(name: "DibsMigrationLog", fields: [
            Field(name: "level", schema: .concrete(DibsSchema.logLevel), required: true),
            Field(name: "message", schema: .concrete(primitiveId(.string)), required: true),
            Field(name: "migration", schema: .concrete(DibsSchema.optionString), required: true),
        ])),
        Schema(id: DibsSchema.migrationServiceFixture, kind: .structure(name: "DibsMigrationServiceFixture", fields: [
            Field(name: "status_request", schema: .concrete(DibsSchema.migrationStatusRequest), required: true),
            Field(name: "status_response", schema: .concrete(DibsSchema.migrationStatusResult), required: true),
            Field(name: "migrate_request", schema: .concrete(DibsSchema.migrateRequest), required: true),
            Field(name: "migrate_response", schema: .concrete(DibsSchema.migrateCallResult), required: true),
            Field(name: "log_item", schema: .concrete(DibsSchema.migrationLog), required: true),
        ])),
    ]
}

public func dibsSquelServiceDescriptor() -> (root: Descriptor, registry: Registry) {
    let root = recordDesc(DibsSchema.squelServiceFixture, DibsSquelServiceFixture.self, fields: [
        fieldAccess(\DibsSquelServiceFixture.schema, schemaInfoDesc()),
        fieldAccess(\DibsSquelServiceFixture.listRequest, listRequestDesc()),
        fieldAccess(\DibsSquelServiceFixture.listResponse, listResultDesc()),
        fieldAccess(\DibsSquelServiceFixture.getRequest, getRequestDesc()),
        fieldAccess(\DibsSquelServiceFixture.getResponse, getResultDesc()),
        fieldAccess(\DibsSquelServiceFixture.createRequest, createRequestDesc()),
        fieldAccess(\DibsSquelServiceFixture.createResponse, rowResultDesc()),
        fieldAccess(\DibsSquelServiceFixture.updateRequest, updateRequestDesc()),
        fieldAccess(\DibsSquelServiceFixture.updateResponse, rowResultDesc()),
        fieldAccess(\DibsSquelServiceFixture.deleteRequest, deleteRequestDesc()),
        fieldAccess(\DibsSquelServiceFixture.deleteResponse, deleteResultDesc()),
    ])
    return (root, Registry(dibsSchemas()))
}

public func dibsMigrationServiceDescriptor() -> (root: Descriptor, registry: Registry) {
    (migrationServiceFixtureDesc(), Registry(dibsSchemas()))
}

private func sampleDibsServiceRow(_ i: UInt32) -> DibsRow {
    DibsRow(fields: [
        DibsRowField(name: "id", value: .i64(1_000 + Int64(i))),
        DibsRowField(name: "name", value: .string("product-\(i)")),
        DibsRowField(name: "metadata", value: .bytes([1, 3, 3, 7, UInt8(i & 0xff)])),
    ])
}

public func sampleDibsSquelServiceFixture() -> DibsSquelServiceFixture {
    let row = sampleDibsServiceRow(7)
    return DibsSquelServiceFixture(
        schema: DibsSchemaInfo(tables: [
            DibsTableInfo(
                name: "products",
                columns: [
                    DibsColumnInfo(
                        name: "id",
                        sqlType: "BIGINT",
                        rustType: "i64",
                        nullable: false,
                        defaultValue: "generated always as identity",
                        primaryKey: true,
                        unique: true,
                        autoGenerated: true,
                        long: false,
                        label: false,
                        enumVariants: [],
                        doc: "Primary key",
                        lang: nil,
                        icon: "key",
                        subtype: nil
                    ),
                    DibsColumnInfo(
                        name: "name",
                        sqlType: "TEXT",
                        rustType: "String",
                        nullable: false,
                        defaultValue: nil,
                        primaryKey: false,
                        unique: false,
                        autoGenerated: false,
                        long: false,
                        label: true,
                        enumVariants: [],
                        doc: "Display name",
                        lang: "en",
                        icon: nil,
                        subtype: nil
                    ),
                ],
                foreignKeys: [
                    DibsForeignKeyInfo(
                        columns: ["owner_id"],
                        referencesTable: "users",
                        referencesColumns: ["id"]
                    ),
                ],
                indices: [
                    DibsIndexInfo(
                        name: "products_name_idx",
                        columns: [DibsIndexColumnInfo(name: "name", order: "ASC", nulls: "LAST")],
                        unique: false,
                        whereClause: "deleted_at IS NULL"
                    ),
                ],
                sourceFile: "crates/app/src/schema.rs",
                sourceLine: 42,
                doc: "Products available in the catalog",
                icon: "box"
            ),
        ]),
        listRequest: DibsListRequest(
            table: "products",
            filters: [
                DibsFilter(
                    field: "name",
                    op: .iLike,
                    value: .string("phon%"),
                    values: [.string("phon"), .string("vox")]
                ),
            ],
            sort: [DibsSort(field: "created_at", dir: .desc)],
            limit: 50,
            offset: 100,
            select: ["id", "name", "metadata"]
        ),
        listResponse: .ok(DibsServiceListResponse(
            rows: [row, sampleDibsServiceRow(8)],
            total: 2
        )),
        getRequest: DibsGetRequest(table: "products", pk: .i64(1_007)),
        getResponse: .ok(row),
        createRequest: DibsCreateRequest(table: "products", data: row),
        createResponse: .ok(row),
        updateRequest: DibsUpdateRequest(table: "products", pk: .i64(1_007), data: row),
        updateResponse: .err(.unknownColumn("legacy_name")),
        deleteRequest: DibsDeleteRequest(table: "products", pk: .i64(1_007)),
        deleteResponse: .ok(1)
    )
}

public func sampleDibsMigrationServiceFixture() -> DibsMigrationServiceFixture {
    DibsMigrationServiceFixture(
        statusRequest: DibsMigrationStatusRequest(
            databaseUrl: "postgres://localhost/app"
        ),
        statusResponse: .ok([
            DibsMigrationInfo(
                version: "202606050701_add_trace_indexes",
                name: "add trace indexes",
                applied: true,
                appliedAt: "2026-06-05T07:03:22Z",
                sourceFile: "crates/app-db/src/migrations/m202606050701_add_trace_indexes.rs",
                source: "CREATE INDEX trace_idx ON trace_event (trace_id);"
            ),
            DibsMigrationInfo(
                version: "202606051142_add_dibs_admin_views",
                name: "add dibs admin views",
                applied: false,
                appliedAt: nil,
                sourceFile: "crates/app-db/src/migrations/m202606051142_add_dibs_admin_views.rs",
                source: nil
            ),
        ]),
        migrateRequest: DibsMigrateRequest(
            databaseUrl: "postgres://localhost/app",
            migration: nil
        ),
        migrateResponse: .ok(DibsMigrateResult(
            totalDefined: 2,
            alreadyApplied: [
                DibsAppliedMigration(
                    version: "202606050701_add_trace_indexes",
                    appliedAt: "2026-06-05T07:03:22Z"
                ),
            ],
            applied: [
                DibsRanMigration(
                    version: "202606051142_add_dibs_admin_views",
                    durationMs: 38
                ),
            ],
            setupMs: 7,
            totalTimeMs: 45
        )),
        logItem: DibsMigrationLog(
            level: .info,
            message: "Applied 202606051142_add_dibs_admin_views (38ms)",
            migration: "202606051142_add_dibs_admin_views"
        )
    )
}
