//! Proof-of-concept: Generate Swift code from rapace service definitions
//!
//! This binary demonstrates Swift code generation from the ServiceRegistry.

use rapace::prelude::*;
use rapace::registry::ServiceRegistry;
use rapace_swift_codegen::SwiftCodegen;

// ============================================================================
// Define a sample service (similar to browser-tests-proto)
// ============================================================================

/// Request payload describing a list of integers.
#[derive(Clone, Debug, facet::Facet)]
pub struct NumbersRequest {
    pub values: Vec<i32>,
}

/// Statistical summary returned by `summarize_numbers`.
#[derive(Clone, Debug, facet::Facet)]
pub struct NumbersSummary {
    pub sum: i64,
    pub mean: f64,
    pub min: i32,
    pub max: i32,
}

/// Request payload for transforming a phrase.
#[derive(Clone, Debug, facet::Facet)]
pub struct PhraseRequest {
    pub phrase: String,
    pub shout: bool,
}

/// Response payload for the phrase transformation.
#[derive(Clone, Debug, facet::Facet)]
pub struct PhraseResponse {
    pub title: String,
    pub original_len: u32,
}

/// Streaming item produced by the countdown RPC.
#[derive(Clone, Debug, facet::Facet)]
pub struct CountEvent {
    pub value: u32,
    pub remaining: u32,
}

/// A person with optional address
#[derive(Clone, Debug, facet::Facet)]
pub struct Person {
    pub name: String,
    pub age: u32,
    pub email: Option<String>,
    pub tags: Vec<String>,
}

/// Example enum for testing enum introspection
#[derive(Clone, Debug, facet::Facet)]
#[repr(u8)]
pub enum Status {
    Pending,
    Active,
    Completed { result: String },
    Failed { error: String, code: i32 },
}

/// Service exercised by the browser tests.
#[allow(async_fn_in_trait)]
#[rapace::service]
pub trait BrowserDemo {
    /// Compute aggregate statistics over an arbitrary sequence of integers.
    async fn summarize_numbers(&self, input: NumbersRequest) -> NumbersSummary;

    /// Transform a phrase and optionally "shout" it.
    async fn transform_phrase(&self, request: PhraseRequest) -> PhraseResponse;

    /// Stream a countdown starting from `start` down to zero.
    async fn countdown(&self, start: u32) -> Streaming<CountEvent>;

    /// Get a person by name.
    async fn get_person(&self, name: String) -> Option<Person>;

    /// Get current status.
    async fn get_status(&self) -> Status;
}

// ============================================================================
// Main: Generate Swift code from registry
// ============================================================================

fn main() {
    println!("=== Rapace Swift Codegen ===\n");

    // Populate the global registry by calling the register function
    // (generated by the #[rapace::service] macro)
    ServiceRegistry::with_global_mut(|registry| {
        browser_demo_register(registry);
    });

    // Generate Swift code
    let mut codegen = SwiftCodegen::new();
    ServiceRegistry::with_global(|registry| {
        println!("Generating Swift for {} services, {} methods\n",
            registry.service_count(), registry.method_count());
        codegen.generate_from_registry(registry);
    });

    // Output the generated Swift
    let swift_code = codegen.into_output();
    println!("Generated Swift code:\n");
    println!("================================================================================");
    println!("{}", swift_code);
    println!("================================================================================");

    // Also write to file
    let output_path = "Generated.swift";
    std::fs::write(output_path, &swift_code).expect("Failed to write output file");
    println!("\n✓ Written to {}", output_path);
}
