// Roam wire protocol types and utilities

export {
  RpcError,
  RpcErrorCode,
  decodeUserError,
} from "./rpc_error.ts";

export type {
  ConnectionId,
  Parity,
  ConnectionSettings,
  MetadataValue,
  MetadataFlags,
  MetadataEntry,
  Hello,
  HelloYourself,
  ProtocolError,
  ConnectionOpen,
  ConnectionAccept,
  ConnectionReject,
  ConnectionClose,
  RequestId,
  MethodId,
  ChannelId,
  RequestCall,
  RequestResponse,
  RequestCancel,
  RequestBody,
  RequestMessage,
  ChannelItem,
  ChannelClose,
  ChannelReset,
  ChannelGrantCredit,
  ChannelBody,
  ChannelMessage,
  Ping,
  Pong,
  SchemaMessage,
  MessagePayload,
  Message,
  Metadata,
  MessageHello,
  MessageHelloYourself,
  MessageProtocolError,
  MessagePing,
  MessagePong,
  MessageConnect,
  MessageAccept,
  MessageReject,
  MessageGoodbye,
  MessageRequest,
  MessageResponse,
  MessageCancel,
  MessageData,
  MessageClose,
  MessageReset,
  MessageCredit,
} from "./types.ts";

export {
  MessageDiscriminant,
  MetadataValueDiscriminant,
  RequestBodyDiscriminant,
  ChannelBodyDiscriminant,
} from "./types.ts";

export {
  MetadataFlagValues,
  parityOdd,
  parityEven,
  connectionSettings,
  helloV7,
  helloYourself,
  metadataString,
  metadataBytes,
  metadataU64,
  metadataEntry,
  messageHello,
  messageHelloYourself,
  messageProtocolError,
  messagePing,
  messagePong,
  messageConnect,
  messageAccept,
  messageReject,
  messageGoodbye,
  messageRequest,
  messageResponse,
  messageCancel,
  messageData,
  messageClose,
  messageReset,
  messageCredit,
} from "./types.ts";

export {
  encodeMessage,
  decodeMessage,
} from "./codec.ts";

export {
  MessageSchema,
  wireMessageSchemasCbor,
  wireSchemaRegistry,
} from "./schemas.ts";
