// @generated by cargo xtask codegen --typescript
// DO NOT EDIT — regenerate with `cargo xtask codegen --typescript`

export type ConnectionId = bigint;

export interface ProtocolError {
  description: string;
}

export type Parity =
  | { tag: "Odd" }
  | { tag: "Even" };

export interface ConnectionSettings {
  parity: Parity;
  max_concurrent_requests: number;
}

export type MetadataValue =
  | { tag: "String"; value: string }
  | { tag: "Bytes"; value: Uint8Array }
  | { tag: "U64"; value: bigint };

export type MetadataFlags = bigint;

export interface MetadataEntry {
  key: string;
  value: MetadataValue;
  flags: MetadataFlags;
}

export interface ConnectionOpen {
  connection_settings: ConnectionSettings;
  metadata: MetadataEntry[];
}

export interface ConnectionAccept {
  connection_settings: ConnectionSettings;
  metadata: MetadataEntry[];
}

export interface ConnectionReject {
  metadata: MetadataEntry[];
}

export interface ConnectionClose {
  metadata: MetadataEntry[];
}

export type RequestId = bigint;

export type MethodId = bigint;

export type ChannelId = bigint;

export type CborPayload = Uint8Array;

export interface RequestCall {
  method_id: MethodId;
  channels: ChannelId[];
  metadata: MetadataEntry[];
  args: Uint8Array;
  schemas: CborPayload;
}

export interface RequestResponse {
  channels: ChannelId[];
  metadata: MetadataEntry[];
  ret: Uint8Array;
  schemas: CborPayload;
}

export interface RequestCancel {
  metadata: MetadataEntry[];
}

export type RequestBody =
  | { tag: "Call"; value: RequestCall }
  | { tag: "Response"; value: RequestResponse }
  | { tag: "Cancel"; value: RequestCancel };

export interface RequestMessage {
  id: RequestId;
  body: RequestBody;
}

export interface ChannelItem {
  item: Uint8Array;
}

export interface ChannelClose {
  metadata: MetadataEntry[];
}

export interface ChannelReset {
  metadata: MetadataEntry[];
}

export interface ChannelGrantCredit {
  additional: number;
}

export type ChannelBody =
  | { tag: "Item"; value: ChannelItem }
  | { tag: "Close"; value: ChannelClose }
  | { tag: "Reset"; value: ChannelReset }
  | { tag: "GrantCredit"; value: ChannelGrantCredit };

export interface ChannelMessage {
  id: ChannelId;
  body: ChannelBody;
}

export interface Ping {
  nonce: bigint;
}

export interface Pong {
  nonce: bigint;
}

export type MessagePayload =
  | { tag: "ProtocolError"; value: ProtocolError }
  | { tag: "ConnectionOpen"; value: ConnectionOpen }
  | { tag: "ConnectionAccept"; value: ConnectionAccept }
  | { tag: "ConnectionReject"; value: ConnectionReject }
  | { tag: "ConnectionClose"; value: ConnectionClose }
  | { tag: "RequestMessage"; value: RequestMessage }
  | { tag: "ChannelMessage"; value: ChannelMessage }
  | { tag: "Ping"; value: Ping }
  | { tag: "Pong"; value: Pong };

export interface Message {
  connection_id: ConnectionId;
  payload: MessagePayload;
}

export const ParityDiscriminant = {
  Odd: 0,
  Even: 1,
} as const;

export const MetadataValueDiscriminant = {
  String: 0,
  Bytes: 1,
  U64: 2,
} as const;

export const RequestBodyDiscriminant = {
  Call: 0,
  Response: 1,
  Cancel: 2,
} as const;

export const ChannelBodyDiscriminant = {
  Item: 0,
  Close: 1,
  Reset: 2,
  GrantCredit: 3,
} as const;

export const MessagePayloadDiscriminant = {
  ProtocolError: 0,
  ConnectionOpen: 1,
  ConnectionAccept: 2,
  ConnectionReject: 3,
  ConnectionClose: 4,
  RequestMessage: 5,
  ChannelMessage: 6,
  Ping: 7,
  Pong: 8,
} as const;

export type ParityOdd = Extract<Parity, { tag: "Odd" }>;
export type ParityEven = Extract<Parity, { tag: "Even" }>;

export type MetadataValueString = Extract<MetadataValue, { tag: "String" }>;
export type MetadataValueBytes = Extract<MetadataValue, { tag: "Bytes" }>;
export type MetadataValueU64 = Extract<MetadataValue, { tag: "U64" }>;

export type RequestBodyCall = Extract<RequestBody, { tag: "Call" }>;
export type RequestBodyResponse = Extract<RequestBody, { tag: "Response" }>;
export type RequestBodyCancel = Extract<RequestBody, { tag: "Cancel" }>;

export type ChannelBodyItem = Extract<ChannelBody, { tag: "Item" }>;
export type ChannelBodyClose = Extract<ChannelBody, { tag: "Close" }>;
export type ChannelBodyReset = Extract<ChannelBody, { tag: "Reset" }>;
export type ChannelBodyGrantCredit = Extract<ChannelBody, { tag: "GrantCredit" }>;

export type MessagePayloadProtocolError = Extract<MessagePayload, { tag: "ProtocolError" }>;
export type MessagePayloadConnectionOpen = Extract<MessagePayload, { tag: "ConnectionOpen" }>;
export type MessagePayloadConnectionAccept = Extract<MessagePayload, { tag: "ConnectionAccept" }>;
export type MessagePayloadConnectionReject = Extract<MessagePayload, { tag: "ConnectionReject" }>;
export type MessagePayloadConnectionClose = Extract<MessagePayload, { tag: "ConnectionClose" }>;
export type MessagePayloadRequestMessage = Extract<MessagePayload, { tag: "RequestMessage" }>;
export type MessagePayloadChannelMessage = Extract<MessagePayload, { tag: "ChannelMessage" }>;
export type MessagePayloadPing = Extract<MessagePayload, { tag: "Ping" }>;
export type MessagePayloadPong = Extract<MessagePayload, { tag: "Pong" }>;
