//! High-level SHM bootstrap helpers over control connections.
//!
//! This module layers host orchestration (`HostHub`) on top of the shared
//! bootstrap wire primitives from `shm_primitives::bootstrap`.

use std::io;

use shm_primitives::PeerId;
pub use shm_primitives::bootstrap::{
    BOOTSTRAP_REQUEST_LEN, BOOTSTRAP_REQUEST_MAGIC, BOOTSTRAP_RESPONSE_HEADER_LEN,
    BOOTSTRAP_RESPONSE_MAGIC, BootstrapError, BootstrapRequest, BootstrapResponseOwned,
    BootstrapResponseRef, BootstrapStatus, decode_request, decode_response, encode_request,
    encode_response,
};
pub use shm_primitives::bootstrap::{
    BootstrapSuccessNames, ReceivedBootstrapResponseStream, recv_response_stream,
    send_response_stream,
};

use crate::host::{GuestSpawnTicket, HostHub, HostPeer};
use crate::segment::Segment;

pub use crate::host::PreparedPeer;
#[cfg(windows)]
pub use crate::host::guest_link_from_names;
#[cfg(unix)]
pub use crate::host::{guest_link_from_raw, guest_link_from_ticket};

/// Result of preparing one bootstrap success response for a guest.
pub struct PreparedBootstrapPeer {
    pub host_peer: HostPeer,
    pub guest_ticket: GuestSpawnTicket,
    pub response_frame: Vec<u8>,
}

impl PreparedBootstrapPeer {
    pub fn peer_id(&self) -> PeerId {
        self.guest_ticket.peer_id
    }
}

impl HostHub {
    /// Reserve a peer and prepare a success response frame for bootstrap.
    ///
    /// `payload` is application-defined response data (typically the segment path).
    pub fn prepare_bootstrap_success(&self, payload: &[u8]) -> io::Result<PreparedBootstrapPeer> {
        let prepared = self.prepare_peer()?;
        let (host_peer, guest_ticket) = prepared.into_parts();
        let response_frame = encode_response(
            BootstrapStatus::Success,
            guest_ticket.peer_id.get() as u32,
            payload,
        )
        .map_err(|err| io::Error::other(format!("failed to encode bootstrap response: {err}")))?;

        Ok(PreparedBootstrapPeer {
            host_peer,
            guest_ticket,
            response_frame,
        })
    }

    /// Build an error response frame for bootstrap request rejection.
    pub fn bootstrap_error_response(&self, message: &[u8]) -> io::Result<Vec<u8>> {
        encode_response(BootstrapStatus::Error, 0, message)
            .map_err(|err| io::Error::other(format!("failed to encode bootstrap error: {err}")))
    }
}

#[cfg(unix)]
impl PreparedBootstrapPeer {
    /// Send the prepared success response and bootstrap fds on Unix.
    ///
    /// r[impl shm.bootstrap.success]
    /// r[impl shm.bootstrap.unix]
    pub fn send_success_unix(
        &self,
        control_fd: std::os::fd::RawFd,
        segment: &Segment,
    ) -> Result<(), BootstrapError> {
        let fds = shm_primitives::bootstrap::BootstrapSuccessFds {
            doorbell_fd: self.guest_ticket.doorbell.as_raw_fd(),
            segment_fd: segment.as_raw_fd(),
            mmap_rx_fd: self.guest_ticket.mmap_rx.as_raw_fd(),
            mmap_tx_fd: self.guest_ticket.mmap_tx_fd,
        };

        shm_primitives::bootstrap::send_response_unix(
            control_fd,
            BootstrapStatus::Success,
            self.guest_ticket.peer_id.get() as u32,
            // This was generated by prepare_bootstrap_success; decode+reuse keeps one source.
            decode_response(&self.response_frame)?.payload,
            Some(&fds),
        )
    }
}

impl PreparedBootstrapPeer {
    /// Send the prepared success response over a byte stream (no fd-passing).
    ///
    /// The payload encodes `{segment_path}\0{doorbell_pipe}\0{mmap_ctrl_pipe}`
    /// so the guest can connect by name.
    ///
    /// r[impl shm.bootstrap.success]
    pub fn send_success_stream(
        &self,
        stream: &mut impl io::Write,
        segment: &Segment,
    ) -> Result<(), BootstrapError> {
        let names = BootstrapSuccessNames {
            segment_path: segment
                .path()
                .to_str()
                .ok_or_else(|| {
                    BootstrapError::Io(io::Error::new(
                        io::ErrorKind::InvalidData,
                        "segment path is not valid UTF-8",
                    ))
                })?
                .to_string(),
            doorbell_name: self.guest_ticket.doorbell_arg(),
            mmap_ctrl_name: self.guest_ticket.mmap_rx_arg(),
        };
        let payload = names.encode();

        send_response_stream(
            stream,
            BootstrapStatus::Success,
            self.guest_ticket.peer_id.get() as u32,
            &payload,
        )
    }
}

// ---------------------------------------------------------------------------
// ShmLinkSource — guest-side bootstrap via control socket
// ---------------------------------------------------------------------------

/// A [`LinkSource`](vox_core::LinkSource) that bootstraps an SHM connection
/// by connecting to a host's control socket.
///
/// Each call to `next_link` performs the full bootstrap handshake: connect to
/// the Unix socket, send the request magic, receive FDs + segment path, attach
/// the segment, and build an `ShmLink`.
#[cfg(unix)]
pub struct ShmLinkSource {
    control_socket_path: String,
}

#[cfg(unix)]
pub fn shm_link_source(control_socket_path: impl Into<String>) -> ShmLinkSource {
    ShmLinkSource {
        control_socket_path: control_socket_path.into(),
    }
}

#[cfg(unix)]
impl vox_core::LinkSource for ShmLinkSource {
    type Link = crate::ShmLink;

    async fn next_link(&mut self) -> io::Result<vox_core::Attachment<Self::Link>> {
        let path = self.control_socket_path.clone();
        let link = tokio::task::spawn_blocking(move || shm_bootstrap_guest(&path))
            .await
            .map_err(|e| io::Error::other(format!("bootstrap task panicked: {e}")))??;
        Ok(vox_core::Attachment::initiator(link))
    }
}

#[cfg(unix)]
fn shm_bootstrap_guest(control_socket_path: &str) -> io::Result<crate::ShmLink> {
    use std::io::Write;
    use std::os::fd::{AsRawFd, IntoRawFd};
    use std::path::Path;
    use std::sync::Arc;
    use std::time::{Duration, Instant};

    let request = encode_request();
    let mut stream = std::os::unix::net::UnixStream::connect(control_socket_path)?;
    stream.write_all(&request)?;

    let received = shm_primitives::bootstrap::recv_response_unix(stream.as_raw_fd())
        .map_err(|e| io::Error::other(format!("bootstrap response: {e}")))?;

    if received.response.status != BootstrapStatus::Success {
        return Err(io::Error::other(format!(
            "bootstrap rejected: {}",
            String::from_utf8_lossy(&received.response.payload)
        )));
    }

    let fds = received
        .fds
        .ok_or_else(|| io::Error::other("missing bootstrap FDs"))?;

    let hub_path = std::str::from_utf8(&received.response.payload)
        .map_err(|e| io::Error::other(format!("bootstrap payload not UTF-8: {e}")))?;

    let segment = match Segment::attach_fd(fds.segment_fd) {
        Ok(segment) => segment,
        Err(fd_err) => {
            // Fallback for hosts that provide a path before/without a usable segment fd.
            let deadline = Instant::now() + Duration::from_millis(750);
            let mut last_path_err = None;
            let mut attached = None;
            while Instant::now() < deadline {
                match Segment::attach(Path::new(hub_path)) {
                    Ok(segment) => {
                        attached = Some(segment);
                        break;
                    }
                    Err(err) => {
                        last_path_err = Some(err.to_string());
                        std::thread::sleep(Duration::from_millis(10));
                    }
                }
            }
            attached.ok_or_else(|| {
                io::Error::other(format!(
                    "attach segment failed (fd: {fd_err}; path: {})",
                    last_path_err.unwrap_or_else(|| "unknown path attach error".to_string())
                ))
            })?
        }
    };
    let segment = Arc::new(segment);

    let peer_id = PeerId::new(received.response.peer_id as u8).ok_or_else(|| {
        io::Error::other(format!("invalid peer id {}", received.response.peer_id))
    })?;

    let doorbell_fd = fds.doorbell_fd.into_raw_fd();
    let mmap_rx_fd = fds.mmap_rx_fd.into_raw_fd();
    let mmap_tx_fd = fds.mmap_tx_fd.into_raw_fd();

    // SAFETY: FDs came from SCM_RIGHTS and are owned by us.
    unsafe { guest_link_from_raw(segment, peer_id, doorbell_fd, mmap_rx_fd, mmap_tx_fd, true) }
}
