//! Snark dialect scaffold for Weavy lowering.
//!
//! This module names the target shape before the full lowering implementation
//! exists: validated Snark grammar, scanner, parser, query, recovery, and
//! incremental facts should become typed Snark intrinsics inside canonical
//! Weavy programs.

use weavy::ir::{
    EffectContract, EffectResource, IntrinsicDescriptor, IntrinsicOp, WeavyLowered, WeavyOp,
};

/// A lowered Snark program carried by canonical Weavy ops.
pub type SnarkWeavyLowered = WeavyLowered<SnarkBlockId, SnarkIntrinsic>;

/// One canonical Snark/Weavy operation.
pub type SnarkWeavyOp = WeavyOp<SnarkBlockId, SnarkIntrinsic>;

macro_rules! id_type {
    ($name:ident, $doc:literal) => {
        #[doc = $doc]
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(u32);

        impl $name {
            /// Return the dense numeric identity.
            #[must_use]
            pub const fn get(self) -> u32 {
                self.0
            }
        }
    };
}

id_type!(
    SnarkBlockId,
    "Symbolic block identity in a Snark Weavy lowering."
);
id_type!(
    ParseStateId,
    "Snark parser state identity generated from validated grammar facts."
);
id_type!(
    SymbolId,
    "Snark symbol identity generated from validated grammar facts."
);
id_type!(
    TerminalId,
    "Snark terminal symbol identity generated from validated grammar facts."
);
id_type!(
    NonterminalId,
    "Snark nonterminal symbol identity generated from validated grammar facts."
);
id_type!(
    ProductionId,
    "Snark production identity generated from validated grammar facts."
);
id_type!(
    FieldId,
    "Snark field identity generated from validated grammar facts."
);
id_type!(
    LexModeId,
    "Snark lexical mode identity generated from validated grammar facts."
);
id_type!(
    AliasSequenceId,
    "Snark alias-sequence identity generated from validated grammar facts."
);
id_type!(
    ExternalScannerStateId,
    "Snark external scanner state identity for scanner replay."
);
id_type!(
    StackVersionId,
    "Snark GLR stack-version identity generated by the runtime."
);
id_type!(
    ConflictId,
    "Snark GLR conflict identity generated from parser tables."
);
id_type!(
    LookaheadTokenId,
    "Branch-local lookahead token identity generated by lexing."
);
id_type!(TraceEventId, "Snark parser trace event identity.");
id_type!(TreeEventId, "Snark tree-event identity.");
id_type!(QueryPlanId, "Snark query plan identity.");
id_type!(
    ValidSymbolSetId,
    "Snark external scanner valid-symbol-set identity."
);
id_type!(
    ScannerSnapshotId,
    "Snark serialized external scanner snapshot identity."
);
id_type!(StackMergeKeyId, "Snark GLR stack-merge-key identity.");
id_type!(BranchRankingId, "Snark GLR branch-ranking identity.");
id_type!(ProductionMetadataId, "Snark production metadata identity.");
id_type!(TreeNodeId, "Snark runtime tree-node identity.");
id_type!(QueryCaptureId, "Snark query capture identity.");

/// A domain intrinsic emitted by Snark lowering.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum SnarkIntrinsic {
    /// Read the next token according to a Snark lexical mode.
    Lex {
        /// GLR stack version being lexed.
        version: StackVersionId,
        /// Lexical mode selected by the current parser state.
        mode: LexModeId,
        /// Branch-local lookahead token produced by lexing.
        output: LookaheadTokenId,
    },
    /// Placeholder for an external scanner call.
    ///
    /// This does not define Snark's scanner host ABI. The valid-symbol mask,
    /// cursor, mark-end, result-symbol, EOF, and serialization contracts belong
    /// to the scanner ABI layer before this intrinsic becomes executable.
    CallExternalScanner {
        /// GLR stack version being scanned.
        version: StackVersionId,
        /// Parser state whose valid-symbol set is being offered.
        state: ParseStateId,
        /// Valid-symbol mask offered to the scanner.
        valid_symbols: ValidSymbolSetId,
        /// Scanner state selected by Snark's parser runtime.
        scanner_state: ExternalScannerStateId,
        /// Serialized scanner snapshot before the call.
        before: Option<ScannerSnapshotId>,
        /// Serialized scanner snapshot after the call.
        after: Option<ScannerSnapshotId>,
        /// Branch-local lookahead accepted by the scanner.
        result: Option<LookaheadTokenId>,
    },
    /// Select parser actions for the branch-local lookahead.
    DispatchActions {
        /// GLR stack version being dispatched.
        version: StackVersionId,
        /// Parser state at the stack head.
        state: ParseStateId,
        /// Branch-local lookahead token.
        lookahead: LookaheadTokenId,
    },
    /// Commit a branch-local lookahead to the input cursor.
    CommitLookahead {
        /// GLR stack version whose lookahead is being consumed.
        version: StackVersionId,
        /// Lookahead token being consumed.
        lookahead: LookaheadTokenId,
    },
    /// Shift the current lookahead and enter another parser state.
    Shift {
        /// GLR stack version being shifted.
        version: StackVersionId,
        /// Parser state to enter after the shift.
        state: ParseStateId,
        /// Lookahead token shifted by this action.
        lookahead: LookaheadTokenId,
    },
    /// Reduce a production into a nonterminal symbol.
    Reduce {
        /// GLR stack version being reduced.
        version: StackVersionId,
        /// Production being reduced.
        production: ProductionId,
        /// Production metadata applied by this reduction.
        metadata: ProductionMetadataId,
        /// Symbol emitted by the reduction.
        symbol: NonterminalId,
        /// Optional alias sequence applied to visible children.
        aliases: Option<AliasSequenceId>,
    },
    /// Split a GLR branch for ambiguous actions.
    SplitGlr {
        /// Conflict that caused the split.
        conflict: ConflictId,
        /// Source stack version.
        source: StackVersionId,
        /// Branches created by the split.
        branches: Vec<StackVersionId>,
    },
    /// Merge compatible GLR branches.
    MergeGlr {
        /// Surviving stack version.
        survivor: StackVersionId,
        /// Retired stack version.
        retired: StackVersionId,
        /// Merge compatibility key.
        key: StackMergeKeyId,
        /// Ranking retained for the survivor.
        ranking: BranchRankingId,
    },
    /// Retire a GLR branch that can no longer win.
    RetireBranch {
        /// Stack version being retired.
        version: StackVersionId,
        /// Why this branch was retired.
        reason: BranchRetireReason,
    },
    /// Recover through Snark's generated recovery path.
    Recover {
        /// Parser state whose recovery action is being executed.
        state: ParseStateId,
    },
    /// Emit an observable parser trace event.
    EmitTrace {
        /// Trace event id.
        event: TraceEventId,
    },
    /// Emit a visible syntax node or token event.
    EmitNode {
        /// Symbol represented by the emitted event.
        symbol: SymbolId,
    },
    /// Emit a structured runtime tree event.
    EmitTreeEvent {
        /// Tree event id.
        event: TreeEventId,
    },
    /// Emit a query capture into the query result sink.
    EmitCapture {
        /// Query plan that emitted the capture.
        query: QueryPlanId,
        /// Query capture id.
        capture: QueryCaptureId,
        /// Runtime tree node captured.
        node: TreeNodeId,
        /// Optional field associated with the capture.
        field: Option<FieldId>,
    },
    /// Run a lowered query plan over the current tree/event stream.
    RunQuery {
        /// Query plan id.
        query: QueryPlanId,
    },
}

/// Why a GLR branch was retired by Snark lowering/runtime.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum BranchRetireReason {
    /// Another branch dominated this one.
    Dominated,
    /// The parse table had no viable action.
    NoAction,
    /// A runtime bound retired the branch.
    Limit,
}

impl SnarkIntrinsic {
    /// The Weavy dialect name used by Snark intrinsics.
    pub const DIALECT: &'static str = "snark.tree_sitter";
}

impl IntrinsicOp for SnarkIntrinsic {
    fn descriptor(&self) -> IntrinsicDescriptor {
        let name = match self {
            Self::Lex { .. } => "lex",
            Self::CallExternalScanner { .. } => "call_external_scanner",
            Self::DispatchActions { .. } => "dispatch_actions",
            Self::CommitLookahead { .. } => "commit_lookahead",
            Self::Shift { .. } => "shift",
            Self::Reduce { .. } => "reduce",
            Self::SplitGlr { .. } => "split_glr",
            Self::MergeGlr { .. } => "merge_glr",
            Self::RetireBranch { .. } => "retire_branch",
            Self::Recover { .. } => "recover",
            Self::EmitTrace { .. } => "emit_trace",
            Self::EmitNode { .. } => "emit_node",
            Self::EmitTreeEvent { .. } => "emit_tree_event",
            Self::EmitCapture { .. } => "emit_capture",
            Self::RunQuery { .. } => "run_query",
        };
        IntrinsicDescriptor {
            dialect: Self::DIALECT,
            name,
        }
    }

    fn effect(&self) -> EffectContract {
        match self {
            Self::Lex { .. } => EffectContract::new()
                .read_resource(EffectResource::Input("source"))
                .write_resource(EffectResource::SideChannel("lookahead"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .may_fail(),
            Self::CallExternalScanner { .. } => EffectContract::new()
                .read_resource(EffectResource::Input("source"))
                .read_resource(EffectResource::SideChannel("scanner_state"))
                .write_resource(EffectResource::SideChannel("scanner_state"))
                .write_resource(EffectResource::SideChannel("lookahead"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .may_fail()
                .calls_user_code(),
            Self::DispatchActions { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("parser_stack"))
                .read_resource(EffectResource::SideChannel("lookahead")),
            Self::CommitLookahead { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("lookahead"))
                .advance_resource(EffectResource::Input("source")),
            Self::Shift { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("parser_stack"))
                .read_resource(EffectResource::SideChannel("lookahead"))
                .write_resource(EffectResource::SideChannel("parser_stack")),
            Self::Reduce { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::Sink("tree_events")),
            Self::SplitGlr { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("glr_worklist")),
            Self::MergeGlr { .. } => EffectContract::new()
                .read_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("glr_worklist")),
            Self::RetireBranch { .. } => EffectContract::new()
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::SideChannel("glr_worklist")),
            Self::Recover { .. } => EffectContract::new()
                .read_resource(EffectResource::Input("source"))
                .advance_resource(EffectResource::Input("source"))
                .write_resource(EffectResource::SideChannel("parser_stack"))
                .write_resource(EffectResource::Sink("tree_events"))
                .may_fail(),
            Self::EmitTrace { .. } => {
                EffectContract::new().write_resource(EffectResource::Sink("parser_trace"))
            }
            Self::EmitNode { .. } => {
                EffectContract::new().write_resource(EffectResource::Sink("tree_events"))
            }
            Self::EmitTreeEvent { .. } => {
                EffectContract::new().write_resource(EffectResource::Sink("tree_events"))
            }
            Self::EmitCapture { .. } => {
                EffectContract::new().write_resource(EffectResource::Sink("query_captures"))
            }
            Self::RunQuery { .. } => EffectContract::new()
                .read_resource(EffectResource::Sink("tree_events"))
                .write_resource(EffectResource::Sink("query_captures"))
                .may_fail(),
        }
    }
}

/// Build the empty initial lowered program.
///
/// This is intentionally only a carrier smoke check. Full lowering must fill
/// this with validated Snark parser/scanner/query facts rather than raw
/// recursive grammar interpretation or generated Tree-sitter implementation
/// files.
#[must_use]
pub fn empty_lowered() -> SnarkWeavyLowered {
    WeavyLowered::new(Vec::new())
}

#[cfg(test)]
mod tests {
    use super::*;
    use weavy::ir::{EffectResource, ResourceAccess, ResourceEffect};

    #[test]
    fn intrinsic_descriptors_use_snark_tree_sitter_dialect() {
        let descriptor = SnarkIntrinsic::Shift {
            version: StackVersionId(0),
            state: ParseStateId(7),
            lookahead: LookaheadTokenId(1),
        }
        .descriptor();

        assert_eq!(descriptor.dialect, "snark.tree_sitter");
        assert_eq!(descriptor.name, "shift");
    }

    #[test]
    fn lex_and_scanner_effects_are_branch_local_until_commit() {
        let lex_effect = SnarkIntrinsic::Lex {
            version: StackVersionId(0),
            mode: LexModeId(3),
            output: LookaheadTokenId(1),
        }
        .effect();
        assert!(lex_effect.resources.contains(&ResourceEffect {
            resource: EffectResource::Input("source"),
            access: ResourceAccess::Read,
        }));
        assert!(!lex_effect.resources.contains(&ResourceEffect {
            resource: EffectResource::Input("source"),
            access: ResourceAccess::Advance,
        }));
        assert!(lex_effect.resources.contains(&ResourceEffect {
            resource: EffectResource::SideChannel("lookahead"),
            access: ResourceAccess::Write,
        }));

        let scanner_effect = SnarkIntrinsic::CallExternalScanner {
            version: StackVersionId(0),
            state: ParseStateId(7),
            valid_symbols: ValidSymbolSetId(3),
            scanner_state: ExternalScannerStateId(2),
            before: Some(ScannerSnapshotId(0)),
            after: Some(ScannerSnapshotId(1)),
            result: Some(LookaheadTokenId(4)),
        }
        .effect();
        assert!(!scanner_effect.resources.contains(&ResourceEffect {
            resource: EffectResource::Input("source"),
            access: ResourceAccess::Advance,
        }));
        assert!(scanner_effect.calls_user_code);

        let commit_effect = SnarkIntrinsic::CommitLookahead {
            version: StackVersionId(0),
            lookahead: LookaheadTokenId(5),
        }
        .effect();
        assert!(commit_effect.resources.contains(&ResourceEffect {
            resource: EffectResource::Input("source"),
            access: ResourceAccess::Advance,
        }));
    }

    #[test]
    fn empty_lowered_has_no_program_or_blocks() {
        let lowered = empty_lowered();

        assert!(lowered.program.is_empty());
        assert!(lowered.blocks.is_empty());
    }
}
