// Schema tracker for schema exchange.
//
// Receives CBOR-encoded SchemaPayload from the remote peer, stores
// WireSchema objects, and provides TranslationPlans for decoding.

// r[impl schema.tracking.received]
// r[impl schema.translation.field-matching]
// r[impl schema.translation.skip-unknown]
// r[impl schema.translation.fill-defaults]
// r[impl schema.translation.reorder]
// r[impl schema.errors.early-detection]
// r[impl schema.errors.type-mismatch]
// r[impl schema.errors.missing-required]

import type {
  WireSchema,
  WireSchemaRegistry,
  WireTypeRef,
  SchemaHash,
  TranslationPlan,
  SchemaSet,
  WireBindingDirection,
} from "@bearcove/roam-postcard";
import { buildPlan, resolveWireTypeRef } from "@bearcove/roam-postcard";
import { encodeSchemaPayload, decodeSchemaPayload } from "./schema_cbor.ts";
import { roamLogger } from "./logger.ts";

function debugJson(value: unknown): string {
  return JSON.stringify(value, (_key, item) => typeof item === "bigint" ? item.toString() : item);
}

/**
 * Tracks schemas received from the remote peer and provides
 * TranslationPlans for decoding with schema evolution.
 */
export class SchemaTracker {
  private schemas = new Map<SchemaHash, WireSchema>();
  private methodBindings = new Map<string, { rootRef: WireTypeRef }>();

  reset(): void {
    this.schemas.clear();
    this.methodBindings.clear();
  }

  /**
   * Record a CBOR-encoded SchemaPayload from the remote peer.
   */
  recordReceived(
    methodId: bigint,
    direction: WireBindingDirection,
    cborBytes: Uint8Array,
  ): void {
    const payload = decodeSchemaPayload(cborBytes);
    const resolvedRootKind = resolveWireTypeRef(payload.root, new Map([
      ...this.schemas,
      ...payload.schemas.map((schema) => [schema.id, schema] as const),
    ]));

    for (const schema of payload.schemas) {
      this.schemas.set(schema.id, schema);
    }
    this.methodBindings.set(this.bindingKey(methodId, direction), {
      rootRef: payload.root,
    });

    roamLogger()?.debug(
      `[roam:schema] recorded ${payload.schemas.length} schemas for method=${methodId} direction=${direction} root=${debugJson(payload.root)} resolved=${resolvedRootKind?.tag ?? "missing"}`,
    );
  }

  /**
   * Build a TranslationPlan for decoding remote args of a method.
   *
   * @param methodId - The method ID
   * @param localSchemaSet - The local schema set for this method's args
   * @returns TranslationPlan, or null if no remote schema available (identity)
   */
  buildTranslation(
    methodId: bigint,
    direction: WireBindingDirection,
    localSchemaSet: SchemaSet,
  ): { plan: TranslationPlan; remoteSchemaSet: SchemaSet } | null {
    const binding = this.methodBindings.get(this.bindingKey(methodId, direction));
    if (!binding) return null;

    const rootKind = resolveWireTypeRef(binding.rootRef, this.schemas);
    if (!rootKind) return null;

    roamLogger()?.debug(
      `[roam:schema] buildTranslation method=${methodId} direction=${direction} remote=${rootKind.tag} local=${localSchemaSet.root.kind.tag} root=${debugJson(binding.rootRef)}`,
    );

    const rootId = binding.rootRef.tag === "concrete" ? binding.rootRef.type_id : 0n;
    const remoteSchemaSet: SchemaSet = {
      root: { id: rootId, type_params: [], kind: rootKind },
      registry: this.schemas,
    };

    return {
      plan: buildPlan(remoteSchemaSet, localSchemaSet),
      remoteSchemaSet,
    };
  }

  /** Get the registry of all received schemas. */
  getRegistry(): WireSchemaRegistry {
    return this.schemas;
  }

  private bindingKey(methodId: bigint, direction: WireBindingDirection): string {
    return `${methodId}:${direction}`;
  }
}

export class SchemaTranslationError extends Error {
  constructor(message: string) {
    super(`Schema translation error: ${message}`);
    this.name = "SchemaTranslationError";
  }
}

// ============================================================================
// SchemaSendTracker — outbound schema exchange
// ============================================================================

/** Info for a single method's schema exchange requirements. */
export interface MethodSendSchemas {
  /** All transitive type IDs needed for encoding args (in dep order). */
  argsDepIds: bigint[];
  /** Root TypeRef for the args tuple schema. */
  argsRootRef: import("@bearcove/roam-postcard").WireTypeRef;
  /** All transitive type IDs needed for encoding the response (in dep order). */
  responseDepIds: bigint[];
  /** Root TypeRef for the response schema. */
  responseRootRef: import("@bearcove/roam-postcard").WireTypeRef;
}

/** Pre-computed send schema data for a service (generated by roam-codegen). */
export interface ServiceSendSchemas {
  /** All type schemas used by this service. typeId (content hash) → Schema object. */
  schemas: Map<bigint, import("@bearcove/roam-postcard").WireSchema>;
  /** Per-method schema info. method_id (bigint) → schema info. */
  methods: Map<bigint, MethodSendSchemas>;
}

export function localSchemaSetForMethod(
  methodId: bigint,
  direction: WireBindingDirection,
  schemaTable: ServiceSendSchemas,
): SchemaSet | null {
  const methodInfo = schemaTable.methods.get(methodId);
  if (!methodInfo) return null;

  const rootRef = direction === "args" ? methodInfo.argsRootRef : methodInfo.responseRootRef;
  const rootKind = resolveWireTypeRef(rootRef, schemaTable.schemas);
  if (!rootKind) return null;

  const rootId = rootRef.tag === "concrete" ? rootRef.type_id : 0n;
  return {
    root: { id: rootId, type_params: [], kind: rootKind },
    registry: schemaTable.schemas,
  };
}

/**
 * Tracks which method+direction schemas have been sent on a connection.
 *
 * Uses pre-computed schema data from code generation (ServiceSendSchemas).
 * Call `reset()` on reconnect. Call `prepareSchemas()` to get the CBOR bytes
 * to embed in RequestCall.schemas / RequestResponse.schemas.
 */
export class SchemaSendTracker {
  private sentTypeIds = new Set<bigint>();
  private sentMethods = new Set<string>();

  reset(): void {
    this.sentTypeIds.clear();
    this.sentMethods.clear();
  }

  /**
   * Returns CBOR bytes for the SchemaPayload to embed in a
   * request/response for method `methodId` in `direction`.
   * Returns empty Uint8Array if schemas for this method+direction were already sent.
   */
  prepareSchemas(
    methodId: bigint,
    direction: "args" | "response",
    schemaTable: ServiceSendSchemas,
  ): Uint8Array {
    const key = `${methodId}:${direction}`;
    if (this.sentMethods.has(key)) return new Uint8Array(0);
    this.sentMethods.add(key);

    const methodInfo = schemaTable.methods.get(methodId);
    if (!methodInfo) return new Uint8Array(0);

    const deps = direction === "args" ? methodInfo.argsDepIds : methodInfo.responseDepIds;
    const rootRef = direction === "args" ? methodInfo.argsRootRef : methodInfo.responseRootRef;

    const newDeps = deps.filter((id) => !this.sentTypeIds.has(id));
    for (const id of newDeps) this.sentTypeIds.add(id);

    // Collect Schema objects for new deps.
    const schemas = newDeps
      .map((id) => schemaTable.schemas.get(id))
      .filter((s): s is import("@bearcove/roam-postcard").WireSchema => s !== undefined);

    // CBOR-encode the payload using the new internally-tagged format.
    return encodeSchemaPayload({
      schemas,
      root: rootRef,
    });
  }
}
