use rapace_schema::MethodDetail;

use crate::render::{fq_name, hex_u64};

pub fn generate_method_ids(methods: &[MethodDetail]) -> String {
    let mut items = methods
        .iter()
        .map(|m| (fq_name(m), crate::method_id(m)))
        .collect::<Vec<_>>();
    items.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Code generated by rapace-codegen. DO NOT EDIT.\n\n");
    out.push_str("package rapace\n\n");
    out.push_str("var MethodID = map[string]uint64{\n");
    for (name, id) in items {
        out.push_str(&format!("    \"{name}\": {hex},\n", hex = hex_u64(id)));
    }
    out.push_str("}\n");
    out
}
